### ISSUE TITLE
bug: Background color not working

### ISSUE THREAD

**Issue by MusherM** [MeanderingProgrammer/render-markdown.nvim#118]
### Neovim version (nvim -v)

0.10.1

### Operating system

MacOS Sonoma

### Terminal emulator / GUI

iTerm2

### Describe the bug

I dont understand why mine looks so different from the look in the readme

<img width="1680" alt="截屏2024-08-05 22 11 09" src="https://github.com/user-attachments/assets/6cb22a23-1fc7-4d01-ad7d-49c6bd619346">

### Expected behavior

Heading with proper colors

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 5.1.4
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

Installed with Lazy.nvim
```lua
return {
  "MeanderingProgrammer/render-markdown.nvim",
  opts = {},
  -- cmd = { "RenderMarkdown" },
  ft = { "markdown" },
  dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
}
```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
This is just up to the color scheme you use, the demos use https://github.com/folke/tokyonight.nvim.

The heading background highlight groups are `RenderMarkdownH1Bg` ... `RenderMarkdownH6Bg`, which if not directly supported by your color scheme default to `DiffAdd`, `DiffChange`, and `DiffDelete`. The values for those will determine the behavior and you can change them to whatever values you want with:

```lua
require('render-markdown').setup({
    heading = {
        backgrounds = {
            'Group1',
            'Group2',
            'Group3',
            'Group4',
            'Group5',
            'Group6',
        },
    },
})
```

**Comment by MusherM** [comment]
Thx for your reply! I'm now using NVChad and Lazy.nvim, as I type :highlight DiffChange, it give me something like DiffChange    xxx guifg=#605f6f, and I guess that means this hight light group is provided. 

I found similar problems with colors occuring when someone else using AutoSession with base46(color selector of NVChad), and I'm using another session manager, after disabling it, I got highlight background color with color code like #000, but the problem I mentioned remains unsolved.

Now I'm guessing it's related to the plugin loading order of Lazy.nvim or still related to my sessionManager plugin, I'm still digging out, I'd appreciate it if you can provide any advice!

**Comment by MeanderingProgrammer** [comment]
Ah the `DiffChange` in your case provides only `guifg` hence why there is no background. In my case it provides a `guibg`, which I thought was the more usual behavior. You'll need to manually provide / create some highlight groups with a background or use a different color scheme.

**Comment by MusherM** [comment]
Well that makes sense, I found no theme provides BG color in NVChad default themes, maybe that's intentional. I'll continue to dig out how to get a highlight group that matches my color theme.
Really helps, thx a lot

**Comment by MusherM** [comment]
Well ,by adding this to chadrc.lua, I got the bg color, though I still find it not so well-looked like yours haha.
Anyway, that helps!

```lua
M.base46 = {
  theme = "catppuccin",
  hl_override = {
    DiffAdd = {
      bg = "one_bg",
      fg = "orange",
    },
    DiffChange = {
      bg = "one_bg2",
      fg = "blue",
    },
    DiffDelete = {
      bg = "one_bg3",
      fg = "cyan",
    },
  },
}


```
