### ISSUE TITLE
Feat: support Quarto docs

### ISSUE THREAD

**Issue by akthe-at** [MeanderingProgrammer/render-markdown.nvim#119]
### Is your feature request related to a problem? Please describe.

I could be oblivious and this is already supported by I feel like this plug-in takes care of all my markdown rendering needs besides quarto markdown files (.qmd).

### Describe the solution you'd like

I would love if this plug-in could render these file types!

### Describe alternatives you've considered

Using a secondary markdown rendering app like headlines has worked for .qmd files in the past but I'd rather not have double dependencies.

**Comment by MeanderingProgrammer** [comment]
I believe this is the same as: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/76.

The following seemed to work in that case:

```lua
require('render-markdown').setup({
    file_types = { 'markdown', 'quatro' },
})
```

**Comment by akthe-at** [comment]
ahhh its looking like this is an issue with lazy loading! I can get it to trigger if i explicitly add cmd = {"RenderMarkdown"} in my config for the plugin. I am investigating further to figure out why this won't auto enable when opening a quarto document now...will report back here so others may figure this out if they struggle like myself....PS i should have searched the issues better...I don't know why I got lazy this time.

**Comment by akthe-at** [comment]
Adding `event = "LazyFile"` to my lazy config for this plugin and keeping the rest of the regular config items related to cmd and file_types solved this issue for me!

**Comment by akthe-at** [comment]
Adding event = "LazyFile" to my lazy config for this plugin and keeping the rest of the regular config items related to cmd and file_types solved this issue for me!

**Comment by MeanderingProgrammer** [comment]
Yeah, I can see lazy loading having some potential edge cases. Glad it's working :)
