### ISSUE TITLE
feature: Thick borders for headers

### ISSUE THREAD

**Issue by serhez** [MeanderingProgrammer/render-markdown.nvim#123]
### Is your feature request related to a problem? Please describe.

Thick borders are available for code blocks. Could they also be available for headers?

### Describe the solution you'd like

This would require the two lines above and below a header to be empty, so that they can be used to render the thick border. This should not be an issue as standard markdown formatting conventions encourage this. However, it is perhaps good to check the corner case in which such lines are not available (i.e., first and last line of the document) or are not empty.

### Describe alternatives you've considered

N/A.

**Comment by MeanderingProgrammer** [comment]
Feature added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/b7002694a7a794f8d8a6a0cc54769628cf1cf9d8

Can be enabled with:

```lua
require('render-markdown').setup({
    heading = { border = true },
})
```

There were other edge cases, like 2 headings back to back with only a line in-beween them like:

```
# Heading 1

## Heading 2
```

If we overlayed the bottom of the first and the top of the second they would overwrite each other.

Logic attempts to use an overlay but will use virtual lines to add space if it's not available.

**Comment by serhez** [comment]
Thanks! I think it looks pretty amazing, it is visually much more clear now the boundaries between sections in my documents. Example on my setup:

![Screenshot 2024-08-08 at 02 17 05](https://github.com/user-attachments/assets/5f08defa-9311-43e6-a12a-76c25da17b99)

![Screenshot 2024-08-08 at 02 16 33](https://github.com/user-attachments/assets/4b80c1c8-518e-43e4-a888-3b2710103056)

Perhaps I would add a virtual line on top of the first heading if it was on the first line of the document (which is quite common I think), so that it looks consistent with the others.

 The only other extra feature I could see is the possibility to also have level-dependent icons for the virtual lines, so for example the blocks I prepend could be extended to the extra lines. But, honestly, I'm nitpicking here and that feature may be annoying to implement (and also only benefit in very few cases, like using blocks as prefixing icons); this is pretty awesome already, thank you :)

**Comment by MeanderingProgrammer** [comment]
> Perhaps I would add a virtual line on top of the first heading if it was on the first line of the document (which is quite common I think), so that it looks consistent with the others.

Virtual lines above the first line do not work quite how you would expect, this is a known issue in neovim: https://github.com/neovim/neovim/issues/27967.

I actually do add it in either case and you can see it if you press `<C-b>`.

There's a similar issue with table borders when tables are on the first line, unfortunate but no real way around it.

> level-dependent icons for the virtual lines

I think this would only make sense if you use block like icons, like in your case. So all I really need to do is apply the foreground highlight group for part of the line. Will see what I can do :)

**Comment by MeanderingProgrammer** [comment]
Added support to highlight the border with the foreground underneath the heading here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/420058baa6e33f20c096c93bb1df52bc841d9475

This is gated under the `border_prefix` option so you would now do:

```lua
require('render-markdown').setup({
    heading = {
        border = true,
        border_prefix = true,
    },
})
```

**Comment by serhez** [comment]
That's great, thanks!

**Comment by pkazmier** [comment]
Is there anyway to show the virtual line above line 1 when entering a markdown buffer so the L1 heading that starts on line 1 looks consistent with the rest of the headings in the buffer? Is there some way we can feed in a series of keys like: "gg<C-b><C-o>"? Go to first line, Ctl-B, and then jump back to where cursor was when entering the file?

**Comment by pkazmier** [comment]
Okay, I'm not a vim expert, but this gross hack seems to work for me.

```lua
vim.api.nvim_create_autocmd({ "BufReadPost" }, {
  pattern = "*.md",
  callback = function()
    local ctrl_y = vim.api.nvim_replace_termcodes("<c-y>", true, false, true)
    vim.schedule(function()
      local current_position = vim.api.nvim_win_get_cursor(0)
      vim.api.nvim_feedkeys(ctrl_y, "n", true)
      vim.api.nvim_win_set_cursor(0, current_position)
    end)
  end,
})
```

**Comment by pkazmier** [comment]
> Okay, I'm not a vim expert, but this gross hack seems to work for me.

So I’ve been using the above hack successfully for 6 months. Works great and makes the first headline look like the rest.
