### ISSUE TITLE
bug: links with inline code in headings aren't displayed entirely with `heading = { width = "block", },`

### ISSUE THREAD

**Issue by xfzv** [MeanderingProgrammer/render-markdown.nvim#124]
### Neovim version (nvim -v)

NVIM v0.11.0-dev-590+g7031949be-dirty

### Operating system

Linux

### Terminal emulator / GUI

kitty 0.35.2

### Describe the bug

If using inline code for a link in a heading, and also using

```lua
heading = {
      width = "block",
    },
```

then not all characters are displayed.

Screenshots:

```
# [`abc`](https://test.org)
```

![01](https://github.com/user-attachments/assets/ff2109c3-fb13-44f0-8e68-db22e1573659)
![02](https://github.com/user-attachments/assets/d9eec9c0-49a3-454a-8ea8-25c4b8889df9)

```
# [`abcd`](https://test.org)
```

![03](https://github.com/user-attachments/assets/d87118f9-c89e-4529-a4da-da5906781aaf)
![04](https://github.com/user-attachments/assets/3c1c4e04-195b-4b92-8108-b96e2b15f906)

```
# [`abcde`](https://test.org)
```
![05](https://github.com/user-attachments/assets/469463ff-525c-4bf9-94c7-8104b2cc059f)
![06](https://github.com/user-attachments/assets/73023c34-43bd-4a4a-9d0b-f48291ec5dfc)

and so on.

### Expected behavior

All characters are displayed inside the inline code

### Healthcheck output

```console
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.0.5
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
return {
  "MeanderingProgrammer/render-markdown.nvim",
  ft = "markdown",
  opts = {
    heading = {
      width = "block",
    },
  },
}
```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Thanks for reporting this!

The problem is slightly different, it's caused by the link in the heading, not the inline code. Links without inline code have the same problem.

Fixed this here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/f365cef5c1d05fd2dd390e1830d5c41f2d1f2121

Please update and LMK if it works for you
