### ISSUE TITLE
feature: Customize header background width for each header type

### ISSUE THREAD

**Issue by ntn-nicholas** [MeanderingProgrammer/render-markdown.nvim#126]
### Is your feature request related to a problem? Please describe.

Currently, header background widths can either be in 'full' or 'block' mode. Full mode seems to add too much clutter for smaller headers, especially when a lot of them are nested (the rainbow color code is nice, but in terms of style they all have the same impact). However, it is still nice to have full mode enabled for the more major headers, to easily separate between different sections without the need of horizontal line separators.

The feature request is for a way users can customize the header background width *per header types*, and not have the option be applied generally to all header types.

### Describe the solution you'd like

Proposed solution would be to optionally accept a table for `heading.width`, where users can choose what mode to use per header. If less than 6 items are given, the last item can be applied to remaining header types.

Ex: `width = { "full", "full", "block", "block", "block", "block" }`
equivalent to `width = { "full", "full", "block" }`

This is only a suggestion , and any configuration implementation would be great as long as the requested behavior can be distinguished.

### Describe alternatives you've considered

N/A

**Comment by MeanderingProgrammer** [comment]
Sure, added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/f06d19ad58e4977f02f7885ea00c3ecfdfe609ff

Works like in the proposal

**Comment by MeanderingProgrammer** [comment]
Glad you like it, I still prefer the uniform version, but I get it :)

Because of how the values are accessed the following config is also equivalent to yours:

```lua
heading = {
    width = { "full", "full", "block" },
},
```

The last value gets used for any indexes greater than the number of values you provide.
