### ISSUE TITLE
feature: How did you upload these really nice videos?

### ISSUE THREAD

**Issue by rogueWookie** [MeanderingProgrammer/render-markdown.nvim#128]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

Hi ~ 
Not sure where/how to ask this but would you mind sharing how you generated your gif's (I presume they are gif's). The recording is extremely clean and cropped perfectly or so it appears to me. I've been using ffmpeg but I can't get anywhere close to your quality. Maybe you're using another tool (e.g. asciinema)?

### Describe alternatives you've considered

n/a

### Additional information

n/a

**Comment by MeanderingProgrammer** [comment]
Hi there,

Sure I can definitely help with this.

Before I dive into how this currently works for this repo I would say that I wouldn't recommend you take my approach. I recently became aware of the [vhs](https://github.com/charmbracelet/vhs) tool and would definitely recommend you check that out, it basically combines the 3 tools I use into one, and I think does a better job of font rendering as well as being generally more robust and configurable. I might transition this repo to using it as well at some point.

As far as what I currently do all the code for generating the gifs (yes they are gifs) is in the repo. At a high level I use [asciinema](https://github.com/asciinema/asciinema) to generate the casts and the [agg](https://github.com/asciinema/agg) tool to convert the casts into gifs. I orchestrate the interactions with a python script using [pyautogui](https://pyautogui.readthedocs.io/en/latest/).

So to generate the heading demo for example I call [just demo-heading](https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/justfile#L22C1-L22C13) which will effectively run:

```bash
rm -f demo/heading_code.gif
python demo/record.py \
  --cols "60" \
  --rows "30" \
  --file demo/heading_code.md \
  --cast heading_code.cast \
  --content "## Heading 2"
agg heading_code.cast demo/heading_code.gif
rm heading_code.cast
```

I no longer keep the gifs in the repo to avoid users having to download them every time the repo is cloned. So once I have the gif I upload it to Github and link it in the README.

The `record.py` script is [here](https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/demo/record.py). It's specific to my local environment, like the first line:

```python
pyautogui.hotkey("`", "c")
```

is specific to how I have tmux configured locally. You can see this is where I kick of the `asciinema rec` command.

I also found that the current state of the `agg` script didn't do a great job with symbols so I created a fork of it for myself [here](https://github.com/MeanderingProgrammer/cli/tree/main/agg).

Hope this helps :)
