### ISSUE TITLE
feature: Relative and absolute file linking

### ISSUE THREAD

**Issue by realhackcraft** [MeanderingProgrammer/render-markdown.nvim#130]
### Is your feature request related to a problem? Please describe.

I want to link to other files in the same directory, or link to an absolute path on my computer.

### Describe the solution you'd like

conceal [desc](./my_file.any) to (icon: nf-oct-file) desc

### Describe alternatives you've considered

N/A

**Comment by MeanderingProgrammer** [comment]
I'm kind of confused about what you mean. 

Are you saying you want different icons if the file is local?

Does setting `link -> hyperlink` accomplish this?

```lua
require('render-markdown').setup({
    link = { hyperlink = ' ' },
})
```

**Comment by realhackcraft** [comment]
Nevermind. My file path had a space, which is why it doesn't render. Could you make it accept spaces in the path? I tried

```
(test)[01 file.md]
```
and
```
(test)[01\ file.md]

but both didn't work.

```

**Comment by MeanderingProgrammer** [comment]
One minor issue is you have the braces swapped, should be `[test](01 file.md)`, I believe both are valid markdown under some definitions but treesitter does not parse the round parenthesis first version correctly.

Even with that it still does not work and this comes down to how markdown handles spaces in links: https://superuser.com/questions/1170654/how-do-i-add-a-hyperlink-with-spaces-in-it-using-markdown

The correct version of what you're doing looks like so: `[test](<01 file.md>)`, with angle brackets around the link and square brackets before round brackets.

**Comment by realhackcraft** [comment]
Right. I see. Thanks!
