### ISSUE TITLE
feature: Markdown-indemt-mode like org indent mode

### ISSUE THREAD

**Issue by printfdebugging** [MeanderingProgrammer/render-markdown.nvim#134]
### Is your feature request related to a problem? Please describe.

So I very much like the idea of this plugin, as markdown is a widely used format, but I find it very ugly when the concealing toggles for the whole file when changing b/w insert/normal modes. Maybe for one line would be fine.

Emacs has org-indent-mode, where each heading indents everything else by 2 spaces under it (other then same level headings). This way the document is formatted really nicely. Is it possible? I see we currently have left_padding for the code blocks, which doesn't let the cursor move any further. Maybe that can be extended similar to org-indent-mode.

I would love to have everything in markup. At max just the current line be shown as raw markdown. Is it possible?

### Describe the solution you'd like

same as the problem

### Describe alternatives you've considered

same as problem

**Comment by printfdebugging** [comment]
If we have all these, then this plugin paired with `mdeval` will make up for a really great "standard" alternative for org-mode/other note taking apps. Neorg fits my needs, but it's not a widely used standard yet, and most static site generators use markdown.

**Comment by MeanderingProgrammer** [comment]
> So I very much like the idea of this plugin, as markdown is a widely used format, but I find it very ugly when the concealing toggles for the whole file when changing b/w insert/normal modes. Maybe for one line would be fine.

Set `win_options -> conceallevel -> default` to 0, something like:

```lua
require('render-markdown').setup({
    win_options = { conceallevel = { default = 0 } },
})
```

See `:h 'conceallevel'` for more details on the values.

The `concealcursor` value we set (also in `win_options`) is what will allow concealing to only toggle for the current line.

You can change the modes that toggle concealing under the cursor by setting an appropriate `concealcursor` value, see `:h 'concealcursor'`.

More details on `win_options` in the Wiki [here](https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki#window-options).

**Comment by MeanderingProgrammer** [comment]
> Emacs has org-indent-mode, where each heading indents everything else by 2 spaces under it (other then same level headings). This way the document is formatted really nicely. Is it possible? I see we currently have left_padding for the code blocks, which doesn't let the cursor move any further. Maybe that can be extended similar to org-indent-mode.

I can take a look into this, but my first thought is this would not be feesible. Mostly because the indenting would need to capture all block elements and indent them appropriately. Currently the plugin queries for a set of specific elements and modifies them. Applying something to all block children would be a pretty different thing to anything that currently exists. Depending on how much I like any solution I come up with will follow up and let you know.

**Comment by printfdebugging** [comment]
Yes, all the elements including the codeblock, the paragraph, the lists. As if the left margin has been shifted as per the top level heading (toplevel in relative terms). Like every h2 and following one will be under h1 and 3 under 2 and so on. 

```
# Heading 1
  ## Heading 2
    content for heading 2 
    - list item 1
    - list item 2
    ```cpp
    // comment here
    ```
# Heading 3
  content for heading 3
```

**Comment by printfdebugging** [comment]
https://explog.in/static/images/org-indent-mode.png the left one is the org indent mode here. (this is an image from the internet.) Since you were able to do it for the codeblock, would it be hard for the rest? I mean it looks cool, gives the document a nice structure.

**Comment by MeanderingProgrammer** [comment]
I don't know about looks cool, but I can see why people would like it. Even in the example image whoever created it prefers only the headings to be indented over.

My personal preference it to stay close to the underlying buffer text to avoid large shifts in text when editing, but I don't mind providing the capability for others to use, hence all the padding options.

The short answer is this is either a really easy change or a nearly impossible one. It's easy if I can get everything within a heading section and apply an indent across all the lines. If I need to individually handle all node types and the potential ways they can be nested then it becomes nearly impossible.

**Comment by MeanderingProgrammer** [comment]
The `section` nodes made this not too bad, added some level of support here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/277ae65ab14c23525ce3dbc9b812244c1976049e

This is an opt-in feature, to enable it:

```lua
require('render-markdown').setup({
    indent = { enabled = true },
})
```

**Comment by printfdebugging** [comment]
This is great! Thank You!

**Comment by printfdebugging** [comment]
```
            require('render-markdown').setup({
                indent = {
                    enabled = true,
                    per_level = 2;
                },
                win_options = {
                    conceallevel = {
                        default = 0,
                    },
                    concealcursor = {
                        default = 'nvic',
                        rendered = 'nvic',
                    },
                },
            })
```
this is how it looks like. still I am getting the toggling when switching between normal and insert modes (for the whole file, instead of one line). I am doing it wrong probably.

**Comment by printfdebugging** [comment]
[Here's the problem.](https://imgur.com/gallery/render-markdown-conceal-gSRhQzk), and it still pesists. as you see when I go into insert mode, all the concealing goes away.

**Comment by MeanderingProgrammer** [comment]
What concealing specifically are you talking about, the video looks correct to me.

Like which line as an example?

**Comment by MeanderingProgrammer** [comment]
I think we might be using the word conceal to mean different things.

**Comment by printfdebugging** [comment]
Yes, Let me clarify. What I wanted was a way to keep the text same as in render state, when I go to insert mode.

**Comment by printfdebugging** [comment]
Or it should just toggle the current line I am editing (and maybe the node around it). Rest all should render as it is. I mean there is no reason to toggle everything from rendered to raw state when entering insert mode.

**Comment by MeanderingProgrammer** [comment]
Ahhhh, I see, to me concealing means hiding information that is there, so I though you wanted the links to remain concealed in insert mode. In that case forget all the `win_options` stuff.

You'll want to set the `render_modes` option to include all the modes you want to be rendered. So something like:

```lua
require('render-markdown').setup({
    render_modes = { 'n', 'v', 'i', 'c' },
})
```

Include `no` if you want rendering in operator pending mode. Basically expand that list to include any and all modes.

There's an example of this on the Wiki: https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki, it shows the 2 behaviors side by side.

**Comment by printfdebugging** [comment]
I saw the demonstration on the right, and I have been smiling since then (like in the DP) Thanks! that's what I was looking for.

**Comment by printfdebugging** [comment]
Hi, how do I add `operator-pending-mode` to render modes?

**Comment by MeanderingProgrammer** [comment]
Add 'no' to the list
