### ISSUE TITLE
bug: external links don't render in preview mode

### ISSUE THREAD

**Issue by csessh** [MeanderingProgrammer/render-markdown.nvim#135]
### Neovim version (nvim -v)

0.10.1

### Operating system

Fedora 40

### Terminal emulator / GUI

Kitty

### Describe the bug

Unlike [[some link]], which renders to a highlighted link in preview mode, [test](http://someurl.com) doesn't fully convert.

Here's a screenshot:
![Screenshot from 2024-08-14 14-59-18](https://github.com/user-attachments/assets/09277c58-7121-469f-aeae-91cae23cd9b2)

### Expected behavior

the external link should display as a underlined text to indicate a clickable URL with a little globe icon to the left of it. 

### Healthcheck output

```
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.1.3
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- ERROR markdown: highlight not enabled
- OK markdown_inline: parser installed
- ERROR markdown_inline: highlight not enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed


```

### Plugin configuration

```
return {
    "MeanderingProgrammer/render-markdown.nvim",
    opts = {},
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
}

```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
These 2 error messages point to the problem:

```
- ERROR markdown: highlight not enabled
- ERROR markdown_inline: highlight not enabled
```

Concealing the links requires `nvim-treesitter` highlights to be enabled. Your config for `nvim-treesitter` should look something like the following:

```lua
{
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
        require('nvim-treesitter.configs').setup({
            ensure_installed = { 'markdown', 'markdown_inline', ... },
            highlight = { enable = true },
        })
    end,
}
```
