### ISSUE TITLE
bug: enabling the plugin fails

### ISSUE THREAD

**Issue by Cadybara** [MeanderingProgrammer/render-markdown.nvim#136]
### Neovim version (nvim -v)

0.9.5

### Operating system

Debian12

### Terminal emulator / GUI

Tilix

### Describe the bug

when trying to enable the plugin in my markdown file (`:RenderMarkdown enable`) I get an error message

> error executing Lua callback: vim/shared.lua:0: attempt to index a boolean value                                                                                                       
stack traceback:
        vim/shared.lua: in function 'default_buffer_config'
        ...ugged/render-markdown.nvim/lua/render-markdown/state.lua:65: in function 'get_config'
        ...ged/render-markdown.nvim/lua/render-markdown/manager.lua:54: in function 'attach'
        ...ged/render-markdown.nvim/lua/render-markdown/manager.lua:41: in function 'set_all'
        ...plugged/render-markdown.nvim/lua/render-markdown/api.lua:8: in function 'command'
        .../plugged/render-markdown.nvim/plugin/render-markdown.lua:17: in function <.../plugged/render-markdown.nvim/plugin/render-markdown.lua:10>

### Expected behavior

Plugin getting enabled and markdown turning beautiful ;)

### Healthcheck output

```
render-markdown.nvim [version]    
- OK plugin 6.1.3                                                                                                                                                                              
- WARNING neovim < 0.10 some features will not work    
     
render-markdown.nvim [configuration]      
- OK valid    
     
render-markdown.nvim [nvim-treesitter]      
- OK installed    
- OK markdown: parser installed    
- OK markdown: highlight enabled    
- OK markdown_inline: parser installed    
- OK markdown_inline: highlight enabled    
     
render-markdown.nvim [executables]      
- OK none to check    
     
render-markdown.nvim [conflicts]      
- OK headlines: not installed    
- WARNING obsidian: installed    
  - ADVICE:    
    - Ensure UI is disabled by setting ui = { enable = false } in obsidian.nvim config    // I did that
    - Acknowledge conflicts to avoid this warning by setting { acknowledge_conflicts = true }
```

### Plugin configuration

default configuration, latex switched off

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Are you attempting to lazy load this plugin somehow? Please provide a more complete picture of your neovim config.

**Comment by Cadybara** [comment]
Updating to the newest nvim version worked for me.
