### ISSUE TITLE
Question: how do I solve conflicting color rendering between treesitter and this plugin

### ISSUE THREAD

**Issue by maulik13** [MeanderingProgrammer/render-markdown.nvim#137]
My changes to `RenderMarkdownH1` variable only changes the icon color and not the actual title. If I run `:Inspect` command on my header I get, `@markup.heading.1.markdown links to rainbow1`. 

Ref: https://github.com/nvim-treesitter/nvim-treesitter/blob/3de418e73d5b912096229aaeea8bb7aef5094e0d/queries/markdown/highlights.scm

I would prefer to have `RenderMarkdownH1` applied to the H1 header, instead of the one applied by the treesitter plugin. Is there any way to achieve this? 

I am using LazyVim latest version with markdown enabled which is using this plugin. Here is its config [from](https://www.lazyvim.org/extras/lang/markdown):

```lua
{
  "MeanderingProgrammer/markdown.nvim",
  opts = {
    file_types = { "markdown", "norg", "rmd", "org" },
    code = {
      sign = false,
      width = "block",
      right_pad = 1,
    },
    heading = {
      sign = true,
    },
  },
  ft = { "markdown", "norg", "rmd", "org" },
  config = function(_, opts)
    require("render-markdown").setup(opts)
    LazyVim.toggle.map("<leader>um", {
      name = "Render Markdown",
      get = function()
        return require("render-markdown.state").enabled
      end,
      set = function(enabled)
        local m = require("render-markdown")
        if enabled then
          m.enable()
        else
          m.disable()
        end
      end,
    })
  end,
}
```

**Comment by maulik13** [comment]
I have tried disabling the highlight from treesitter, but seems that does not fix the issue. 

```lua
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = {
      disable = { "markdown", "markdown_inline" },
    },
  },
}
```

**Comment by MeanderingProgrammer** [comment]
There currently is not, the idea is to let your color scheme pick the heading text color and by default apply the same color to the icon. Changing `RenderMarkdownH1` only changes the icon color.

You can override your color scheme's choice and set whatever value you like for `@markup.heading.1.markdown`. This will then be applied to both H1 text and the icon from this plugin. You can further customize the icon by setting yet another value for `RenderMarkdownH1`.
