### ISSUE TITLE
bug: Checkbox should be at same indentation level as bullet point

### ISSUE THREAD

**Issue by jazzabeanie** [MeanderingProgrammer/render-markdown.nvim#140]
### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system

Ubuntu 22.04

### Terminal emulator / GUI

Terminal

### Describe the bug

A checkbox should have the same indentation level as the indentation level of the bullet point it is attached to.

### Expected behavior

This code:

```
# Some file

Some list:

- blah
- bleh
- [ ] checkbox that should be at same indentation level
```

Generates this:
![image](https://github.com/user-attachments/assets/05252be1-b586-4133-8a4f-359edf2ee013)

By looking at the code you would expect the checkbox to be at the same alignment as the bullet points, but it is further indented giving the impression that it is an item in a sublist.

### Healthcheck output

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.1.8
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

Default for Lazy.vim

### Plugin error log

N/A

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Not a bug. The additional spaces were needed to allow `overlay` virtual text to hide all of the underlying text. I used `overlay` for compatibility with neovim `0.9.x`.

Added this as a new position property for checkboxes here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/275f28943ab9ce6017f90bab56c5b5b3c651c269.

The new `inline` value is the default for users using neovim >= `0.10.0`, so updating the plugin for you should result in the desired alignment.
