### ISSUE TITLE
feature: Lua pattern for custom link works well, but it affects random order

### ISSUE THREAD

**Issue by greyHairChooseLife** [MeanderingProgrammer/render-markdown.nvim#146]
### Is your feature request related to a problem? Please describe.

Here is my current config for the `link` section:

```lua
link = {
    enabled = true,
    image = '󰥶\'',
    hyperlink = '\'',
    highlight = 'RenderMarkdownDocLink',
    custom = {
      -- web = { pattern = '^http[s]?://(?!www%.youtube%.com)(?!youtu%.be)', icon = '󰖟\'', highlight = 'RenderMarkdownWebLink' },
      web = { pattern = '^http[s]?://www', icon = '󰖟\'', highlight = 'RenderMarkdownWebLink' },
      file = { pattern = '^file:', icon = '\'', highlight = 'RenderMarkdownFileLink' },
      youtube = { pattern = '^http[s]?://www%.youtube%.com/.*', icon = '\'', highlight = 'RenderMarkdownYoutubeLink' },
    },
  },
```

As you see, I initially tried 'negative lookahead', but it didn't seemed to be supported.

And I have tested something else, although `pattern = '^http[s]?://www%.youtube%.com/.*'` is a subset of my 'web' pattern above.

I eventually discovered that sometimes, the 'youtube' pattern is evaluated earlier than the one for the 'web'.

### Describe the solution you'd like

It would be great if there were an option to specify the order in which patterns are applied.

### Describe alternatives you've considered

:D

**Comment by MeanderingProgrammer** [comment]
I thought about it some more and prefer the first approach, since I think it captures the idea of more specific patterns being preferred without adding any more overhead.

Implemented it here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/42dbd097d73d8c833f886f35ca3be2065973c628.

Give it a shot and LMK if its what you had in mind!

**Comment by greyHairChooseLife** [comment]
@MeanderingProgrammer 
I agree with your decision; it would be the right way how we use the lua pattern or the regex things.

And thank you for your fast and great work! I've request enhancement last night and it's all completed by the morning!
