### ISSUE TITLE
feature: Mermaid graph support

### ISSUE THREAD

**Issue by h4mr3r** [MeanderingProgrammer/render-markdown.nvim#148]
### Is your feature request related to a problem? Please describe.

When i discovered this genius project - it is the ony think i miss & i often use

### Describe the solution you'd like

I'd like to see built-in support for Mermaid diagrams. Mermaid allows for the easy creation of diagrams and flowcharts which is awesome for this neovim project.

### Describe alternatives you've considered

I do not have one :(

**Comment by MeanderingProgrammer** [comment]
Hi,

Unfortunately this is pretty out of scope for this project. Getting images and rendering working within the terminal is pretty involved.

Luckily others have taken on this work. I suggest checking out: https://github.com/3rd/diagram.nvim, which supports `mermaid` as well as a few other diagram types. 

This plugin shouldn't interfere with that one and the 2 should be able to run side by side.
