### ISSUE TITLE
bug: With default configuration I am getting different visuals

### ISSUE THREAD

**Issue by Divyanshg01** [MeanderingProgrammer/render-markdown.nvim#153]
### Neovim version (nvim -v)

0.10.1

### Operating system

Arch Linux

### Terminal emulator / GUI

Kitty terminal with zsh

### Describe the bug

![image](https://github.com/user-attachments/assets/4cde75e5-92dc-41cd-af4d-dbf03ed51ee5)

When I load the default config and open the markdown files, all the heading  except level 1,2 are in red color
I don't know why it is

### Expected behavior

It should be of different colors and the code blocks are also of different color(black) instead they should be transparent

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.3.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled

render-markdown.nvim [executables] ~
- OK none to check

render-markdown.nvim [conflicts] ~
- OK conflicts acknowledged

### Plugin configuration

```
return {
	"MeanderingProgrammer/render-markdown.nvim",
	opts = {},
	-- dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
	dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.icons" }, -- if you use standalone mini plugins
	-- dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" }, -- if you prefer nvim-web-devicons
	config = function()
		require("render-markdown").setup({
			acknowledge_conflicts = true,
			latex = { enabled = false },
		})
	end,
}
```

### Plugin error log

No error log

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

### Additional information

I am using it with obsidian.nvim but I don't think this behaviour is caused by it still I am providing my obisdian.nvim config

```
return {
    "epwalsh/obsidian.nvim",
    version = "*", -- recommended, use latest release instead of latest commit
    lazy = true,
    ft = "markdown",
    -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
    -- event = {
    --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
    --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/*.md"
    --   -- refer to `:h file-pattern` for more examples
    --   "BufReadPre path/to/my-vault/*.md",
    --   "BufNewFile path/to/my-vault/*.md",
    -- },
    dependencies = {
        -- Required.
        "nvim-lua/plenary.nvim",

        -- see below for full list of optional dependencies 👇
    },
    opts = {

        -- see below for full list of options 👇
    },
    config = function()
        require("obsidian").setup({
            ui = { enable = false },
            workspaces = {
                {
                    name = "personal",
                    path = "~/Documents/Notes",
                },
                {
                    name = "work",
                    path = "~/Documents/Vaults",
                },
            },
        })
    end,
}

```

**Comment by MeanderingProgrammer** [comment]
Not a bug, just the default behavior.

We use the highlight groups `RenderMarkdownH1Bg` .. `RenderMarkdownH6Bg` for the backgrounds.

In the colors section of the README: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#colors, if no values are defined by your color scheme for these highlight groups then `RenderMarkdownH3Bg` .. `RenderMarkdownH6Bg` all link to `DiffDelete`.

You can either:

- Use a color scheme which directly supports this plugin like `tokyonight`, `catppuccin`, and several others
- Define `RenderMarkdownH3Bg` .. `RenderMarkdownH6Bg` as whatever colors you like
- Provide different highlights for the backgrounds: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#headings

  ```lua
  require('render-markdown').setup({
      heading = {
          backgrounds = { 'highlight_1', 'highlight_2', 'highlight_3', 'highlight_4', 'highlight_5', 'highlight_6' },
      },
  })
  ```
