### ISSUE TITLE
bug: Wrong HL color for heading borders

### ISSUE THREAD

**Issue by SimonHoSprung** [MeanderingProgrammer/render-markdown.nvim#154]
### Neovim version (nvim -v)

0.10

### Operating system

Windows 11

### Terminal emulator / GUI

Wezterm

### Describe the bug

I have borders turned on for headings but the color is not the same as the main bg color. Im not sure if this is a bug, or what the correct hlgroup is for heading borders. This is what it looks like:

![image](https://github.com/user-attachments/assets/4ea714cf-4869-4b94-861b-57bb0c77d751)

It seems to be using the fg color instead of the bg color?

This is the case for all headings at all levels:

```
# Heading 1

## Heading 2

### Heading 3

#### Heading 4

##### Heading 5

###### Heading 6
```

![image](https://github.com/user-attachments/assets/a1594ce4-a487-40a7-bccb-acff5eedb30d)

This is how my colors are set:

```
RenderMarkdownH1 = { fg = theme.rainbow.rainbow1 },
RenderMarkdownH2 = { fg = theme.rainbow.rainbow2 },
RenderMarkdownH3 = { fg = theme.rainbow.rainbow3 },
RenderMarkdownH4 = { fg = theme.rainbow.rainbow4 },
RenderMarkdownH5 = { fg = theme.rainbow.rainbow5 },
RenderMarkdownH6 = { fg = theme.rainbow.rainbow6 },

RenderMarkdownH1Bg = { fg = theme.rainbow.rainbow1, bg = <darker rainbow1> },
RenderMarkdownH2Bg = { fg = theme.rainbow.rainbow2, bg = <darker rainbow2> },
RenderMarkdownH3Bg = { fg = theme.rainbow.rainbow3, bg = <darker rainbow3> },
RenderMarkdownH4Bg = { fg = theme.rainbow.rainbow4, bg = <darker rainbow4> },
RenderMarkdownH5Bg = { fg = theme.rainbow.rainbow5, bg = <darker rainbow5> },
RenderMarkdownH6Bg = { fg = theme.rainbow.rainbow6, bg = <darker rainbow6> },
```

### Expected behavior

The background color of a heading + border should be the same

### Healthcheck output

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.3.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

```
  {
    "MeanderingProgrammer/markdown.nvim",
    opts = {
      heading = {
        position = "inline",
        sign = true,
        signs = { "󰫎 " },
        border = true,
        width = "full",
        icons = { " 󰲡 ", " 󰲣 ", " 󰲥 ", " 󰲧 ", " 󰲩 ", " 󰲫 " },
      },
      code = {
        sign = true,
        style = "full",
        width = "block",
        min_width = 60,
        left_pad = 2,
        language_pad = 2,
      },
      pipe_table = {
        preset = "round",
      },
      sign = {
        enabled = true,
        highlight = "RenderMarkdownSign",
      },
    },
  },
```

### Plugin error log

NA

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Should be resolved by: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/12fdb6f6623cb7e20da75be68858f12e1e578ffd

Please update and LMK if it works!

**Comment by SimonHoSprung** [comment]
works great, thanks!
