### ISSUE TITLE
bug: emoji text is not rendered

### ISSUE THREAD

**Issue by jiyeol-lee-kds** [MeanderingProgrammer/render-markdown.nvim#155]
### Neovim version (nvim -v)

0.10.1

### Operating system

MacOS

### Terminal emulator / GUI

Alacritty

### Describe the bug

emoji text like `:running_man:` is not rendered like 🏃🏼‍♂️.

### Expected behavior

When the cursor is in normal mode, I want to render emoji.

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.3.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

```lua
  local render_markdown = require('render-markdown')
  local setup = {
    file_types = { 'markdown' },
    render_modes = { 'n', 'v', 'i', 'c' },
    indent = {
      enabled = false,
      per_level = 0,
    },
    heading = {
      position = 'inline',
      icons = { '[H1]', '[H2]', '[H3]', '[H4]', '[H5]', '[H6]' },
    },
    checkbox = {
      unchecked = { icon = '🌑', highlight = 'RenderMarkdownUnchecked' },
      checked = { icon = '🌕', highlight = 'RenderMarkdownChecked' },
      custom = {
        inprogress_1 = { raw = '[.]', rendered = '🌘', highlight = 'RenderMarkdownTodo' },
        inprogress_2 = { raw = '[o]', rendered = '🌗', highlight = 'RenderMarkdownTodo' },
        inprogress_3 = { raw = '[O]', rendered = '🌖', highlight = 'RenderMarkdownTodo' },
      }
    }
  }

  render_markdown.setup(setup)

  vim.treesitter.language.register('markdown', 'vimwiki')
```

### Plugin error log

No Log

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Where in your config is the text running man and what would make you think this plugin resolved text to emojis?

**Comment by jiyeol-lee-kds** [comment]
> Where in your config is the text running_man?
> 
> Or are you referring to resolving emojis in markdown documents in general?
> 
> That's not a feature stated anywhere as far as I know. Is this because the emojis resolve in Github?

I reported it because emojis resolved in markdown documents when I was only using `vimwiki` but since I added this plugin, it stops to resolve emojis. Do you think I missed some configuration?

**Comment by MeanderingProgrammer** [comment]
Huh I didn't know `vimwiki` had emoji support, but it looks like it does: https://github.com/search?q=repo%3Avimwiki%2Fvimwiki%20emoji&type=code.

I'm not really sure how to configure things so that this plugin does its part of the rendering and `vimwiki` continues to resolve emojis. There's definitely going to be edge cases when 2 plugins try to do rendering.

My first though is that the emojis rely on the conceal level to work. Can you try adding the following to the config:

```
local setup = {
  ...
  win_options = {
    concealcursor = { rendered = 2 },
  },
}
```

**Comment by jiyeol-lee-kds** [comment]
I just tried `rendered = 0`, `rendered = 1`, `rendered = 2` and `rendered = 3` but no luck :(
