### ISSUE TITLE
bug: checkboxes not aligned

### ISSUE THREAD

**Issue by marcocamilo** [MeanderingProgrammer/render-markdown.nvim#158]
### Neovim version (nvim -v)

0.10.0

### Operating system

MacOS

### Terminal emulator / GUI

iTerm

### Describe the bug

Checkboxes aren't aligned according to their indentation level

Raw:
![Raw input](https://github.com/user-attachments/assets/98f60b09-ed99-4ab5-916c-5271f94e9be2)

```
- [x] YAML properties
    - [x] Double title on YAML
    - [x] Pages without properties starting with heading block
    - [x] Parsing empty yaml attributes
    - [ ] Pages without properties starting with heading block
    - [ ] Properties + first bullet yaml attributes
- [x] Block references
    - [x] Normal
    - [x] When referencing code block
    - [x] uid for referenced code blocks
    - [x] Multiple matches in one line
- [x] Aliases
    - [x] Page aliases
    - [x] block aliases
- [x] Code blocks
    - [x] indented code blocks + indented bullets following
- [x] Tags: wrap all in [[]]
- [x] LaTeX
- [x] Images
- [x] Queries
- [ ] Post migration review
    - [x] Parse Date Added
    - [ ] Remaining todos
    - [ ] Overly indented blocks
```

Rendered:
![Rendered output](https://github.com/user-attachments/assets/a76c1976-2c93-4d8f-82d7-9d30be804d14)

### Expected behavior

Checkboxes align by indentation level

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.3.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- WARNING obsidian: installed
  - ADVICE:
    - Ensure UI is disabled by setting ui = { enable = false } in obsidian.nvim config
    - Acknowledge conflicts to avoid this warning by setting { acknowledge_conflicts = true }

### Plugin configuration

"MeanderingProgrammer/render-markdown.nvim",
dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
opts = {
	file_types = { "markdown", "quarto" },
	win_options = {
		conceallevel = {
			rendered = 2,
		},
	},
},

### Plugin error log

N/A

### Confirmations

- [x] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
> I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

Instructions not followed

**Comment by marcocamilo** [comment]
Don't know what you meant with "markdown text for any screenshots", but I hope it's now added. If you need anything else, please do let me know. Thank you in advanced.

**Comment by MeanderingProgrammer** [comment]
Yep that's exactly what the checkbox is supposed to mean. Any suggestions on clearing up the wording? Would removing the word markdown make it more clear, it definitely doesn't read super well.

Issue should be resolved by: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/06337f64367ef1f1115f0a9ba41e49b84a04b1a4

**Comment by MeanderingProgrammer** [comment]
I updated the wording to: "I have provided text for all screenshots & understand that my issue will be closed if I have not"

Does this version make more sense? If you have any suggestions LMK!

**Comment by marcocamilo** [comment]
Awesome! The issue is now resolved! And sure thing, thanks for asking for feedback on the wording. Since I made a few changes to the original post, I'll share with you a wording for each according to which one you meant from the beginning.

- If you're referring to embedding images in markdown syntax, then phrase as: "I have embedded all screenshots in markdown format (i.e. `![](image-link)`)"
- If you meant adding a caption to the markdown image, then phrase as: "Add a caption to the markdown image"
- If you meant copying the content of the screenshot in markdown format, then phrase as: "Provide any screenshot text as a markdown code block (i.e. ```[screenshot text]```)

You can choose from these according to what you meant (I did all of these changes to see if they fit what you wanted). Hope this helps!
