### ISSUE TITLE
bug:  When Reference-style Links used in URL and Images in code block , it happened a nil value

### ISSUE THREAD

**Issue by RaidOpe** [MeanderingProgrammer/render-markdown.nvim#163]
### Neovim version (nvim -v)

0.10

### Operating system

Windows

### Terminal emulator / GUI

Weztem 

### Describe the bug

When Reference-style Links used in URL and Images in code block , it happened a nil value.  It's seem so strict to detect the Ref's format

### Expected behavior

Work normally

### Healthcheck output

Not required

### Plugin configuration

Not required

### Plugin error log

Error executing vim.schedule lua callback: ...render-markdown.nvim/lua/render-markdown/render/code.lua:149: attempt to call field 'inverse_bg' (a nil value)
stack traceback:
        ...render-markdown.nvim/lua/render-markdown/render/code.lua:149: in function 'background'
        ...render-markdown.nvim/lua/render-markdown/render/code.lua:76: in function 'render'
        ...r-markdown.nvim/lua/render-markdown/handler/markdown.lua:39: in function 'callback'
        ...ender-markdown.nvim/lua/render-markdown/core/context.lua:134: in function 'query'
        ...r-markdown.nvim/lua/render-markdown/handler/markdown.lua:34: in function 'parse'
        ...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:173: in function 'parse_tree'
        ...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:141: in function 'parse_buffer'
        ...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:86: in function 'update'
        ...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:57: in function <...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:56>

### Confirmations

- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

### Additional information

```md
[Google][]

[Google]: http://google.com/

![alt text][id]

[id]: /path/to/img.jpg "Title"

```
It works well 

But if this happens

` ``` `md

```md 


[Google][]

[Google]: http://google.com/

![alt text][id]

[id]: /path/to/img.jpg "Title"

```

**Comment by MeanderingProgrammer** [comment]
The plugin configuration and healthcheck are always required.

I am unable to replicate this with your example, try updating the plugin.

**Comment by RaidOpe** [comment]
Unfortunately I didn't get the gif, I ended up surmising that it was an error caused by the upstream treesitter not updating, and I didn't get an error after updating the dependency with Lazy, I'm going to close it
