### ISSUE TITLE
bug: No changes on windows display

### ISSUE THREAD

**Issue by allancomar** [MeanderingProgrammer/render-markdown.nvim#165]
### Neovim version (nvim -v)

NVIM v0.10.2-dev-37+gb55435f438

### Operating system

MacOS

### Terminal emulator / GUI

Kitty

### Describe the bug

there is no conversion of visuals on the neovim window.
![Screenshot 2024-09-12 at 1 52 55 PM](https://github.com/user-attachments/assets/9be4b7d9-47ba-4f28-850d-e408b626f85d)

### Expected behavior

Text and visuals get formated.

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.3.6
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

return {
    "MeanderingProgrammer/render-markdown.nvim",
    opts = {},
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    config = function()
        require("render-markdown").setup({
            file_types = { "markdown" },
            log_level = "debug",
        })
    end
}

### Plugin error log

no logs get generated.

### Confirmations

- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Do you by chance have `lazy = true` set in your `lazy.nvim` config?

If so try:

```lua
return {
  "MeanderingProgrammer/render-markdown.nvim",
  lazy = false,
  dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
  config = function()
    require("render-markdown").setup({})
  end
}
```

**Comment by allancomar** [comment]
same behaviour.
the Lazy interface shows that it loaded the pluggin:
```
    ● render-markdown.nvim 5.59ms  start
```

**Comment by MeanderingProgrammer** [comment]
If you open a markdown file and run `:RenderMarkdown enable` does that do anything?

Also are you using any kind of distro, `LazyVim`, `NvChad`, etc.?

**Comment by allancomar** [comment]
run the RenderMarkdown enable does nothing.
I am not using any distribution.
there is any way to set up the path for the log?

**Comment by MeanderingProgrammer** [comment]
I'm kind of at a loss. The plugin seems to be loading, and even the commands exist, but it just doesn't want to work, so strange.

The log file is at `~/.local/state/nvim/render-markdown.log`, there's no way to change the path, but even if there were I wouldn't expect to see anything. The logs are for debugging something partially running but doing something unexpected. I'll see about adding some logs around attaching to buffers. 

We do rely on a `FileType` event and matching that value which is the main reason the plugin would just skip processing a buffer. Do you disable the filetype extension or anything similar to that you can think of that would cause the buffer to be ignored?

**Comment by allancomar** [comment]
yeah. there wasn´t any file at the location. I don´t think there is anything that disable filetype. I even rely on java file type to attach jdtls. and the icon on the buffer status bar seems to indicate that is a markdown file. I can try to log the FileType while opening the file to see what it produces.

**Comment by MeanderingProgrammer** [comment]
I've made various changes to the debug logs to hopefully figure out what's going on: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/2b86631c153e24682a1a2d05e37a0f4f94e9b827

Can you update the plugin, open a `markdown` file, and if it still doesn't work check if there are any logs.

You can access the log file with `:RenderMarkdown log` now as well.

**Comment by ayozehd** [comment]
@MeanderingProgrammer I'm having same issue as well and all healthchecks are green. I found the new command `:RenderMarkdown log` very useful 👌 

```
stack traceback:
        [C]: in function 'tabnew'
        ...im/lazy/render-markdown.nvim/lua/render-markdown/api.lua:22: in function 'command'
        ...azy/render-markdown.nvim/lua/render-markdown/command.lua:36: in function <...azy/render-markdown.nvim/lua/render-markdown/command.lua:31>
```

**Comment by MeanderingProgrammer** [comment]
Huh, that is so strange, I wish I could help but since I can't re-create what's going on is pretty difficult.

Is there any more to that stacktrace? It just says the `tabnew` vim command failed, which I'm not really sure how / why that would happen.

**Comment by allancomar** [comment]
got the new version. with the latest fix to the table. no success yet, this is the logs from the RenderMarkdown log
```
2024-09-16 08:59:53 DEBUG [attach test.md] - start
2024-09-16 08:59:53 DEBUG [attach test.md] - success
2024-09-16 08:59:53 DEBUG [attach test.md] - start
2024-09-16 08:59:53 DEBUG [attach test.md] - skip | already attached
2024-09-16 08:59:56 DEBUG [attach ] - start
2024-09-16 08:59:56 DEBUG [attach ] - skip | file type | cmp_menu /∈ { "markdown" }
```

**Comment by allancomar** [comment]
Finally understood. if I have vimwiki pluggin installed it prevent yours to work

**Comment by MeanderingProgrammer** [comment]
Ah, there's a small section in the ERADME about that: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#vimwiki.

It's interesting that `vimwiki` doesn't prevent the plugin from attaching to the file, but does prevent it from really running anything.

**Comment by MeanderingProgrammer** [comment]
Found the problem. Something about the way `vimwiki` changes things causes there to be no treesitter parser available for the buffer.

I've made this as an error log here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/2424693c7a4c79641a7ea1e2a838dbc9238d6066

Should be easier to catch in the future.
