### ISSUE TITLE
feature: 

### ISSUE THREAD

**Issue by Kyren223** [MeanderingProgrammer/render-markdown.nvim#168]
### Is your feature request related to a problem? Please describe.

There is no way to configure how things are concealed

### Describe the solution you'd like

Configuration options for the following functionality:
- Whether to show/hide the thing under the cursor in normal mode
- Whether to show/hide the entire file (except cursor or line) in insert mode

The desired goal for me is when going to a mode that isn't normal (insert/visual) I don't want the entire file to get back to normal just because I edit a TODO, so being able to decide to only show the raw text when the cursor is on the thing and not the entire file (like the current normal mode behavior), or even specifying a range like "show only 5 lines around the cursor (2 up, 2 down, 1 current).

Another thing that'd be cool, is in visual mode, only show raw text that is actively selected (or some amount of lines around selections) rather than the entire file.

### Describe alternatives you've considered

N/A

**Comment by MeanderingProgrammer** [comment]
The modes this plugin renders content in is configurable through the `render_modes` option. There's an example of that in the wiki here: https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki#render-modes.

If you want it to render in `insert` and `visual` mode for instance, so they look the same as `normal` mode by default, you would do:

```lua
require('render-markdown').setup({
    render_modes = { 'n', 'v', 'i', 'c' },
})
```

You can expand the list of modes as much as you like to include all the modes you want to be rendered.

I also recently pushed a change which allows `render_modes` to be a boolean: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/7493db6d3fe3f6679549e6020498f72e97cd9b73. So now if you want to have the buffer be rendered in all modes you can simply do:

```lua
require('render-markdown').setup({
    render_modes = true,
})
```

**Comment by MeanderingProgrammer** [comment]
Does the above take care of the feature request or were there specific other things you had in mind?

**Comment by Kyren223** [comment]
Oh thanks I missed it.
For normal and insert mode it works fine but not for visual.
For normal/insert using the cursor is fine, but this isn't good for visual mode, it'd be better if it is based on what's visually selected instead.

**Comment by MeanderingProgrammer** [comment]
Sure, should work after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/5ff191f0c7457ede2fd30ecf76ab16c65118b4ee

**Comment by Kyren223** [comment]
Updated to that commit, seems to still be broken (I think that's because it uses inlay hints?)
![image](https://github.com/user-attachments/assets/348de613-f571-4b64-a76b-1a03b3a5a0ac)

**Comment by MeanderingProgrammer** [comment]
It does not use inlay hints, everything is an `extmark`.

How did you create this selection?

- Did you put your cursor on the `Some Header` line then run something like `10j`? This one should work.
- Did you do some kind of `vi` motion?
- Something else?

There are different types of visual modes and I may not have handled all of them.

**Comment by MeanderingProgrammer** [comment]
I've updated the logic to handle all the visual modes here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/354baf485370b670bb1c1cd64309438607b0465d.

Can you update and try again, should work regardless of what you do to select.

**Comment by Kyren223** [comment]
Yes it works, thanks!
