### ISSUE TITLE
help: how to disable in diff mode

### ISSUE THREAD

**Issue by astephanh** [MeanderingProgrammer/render-markdown.nvim#169]
### Description

I'd like to disable the rendering in diff mode, it gets confusing as the highlighting is pretty close to the diff coloring. Is there an easy way to just disable it if buffer is in diff mode?

**Comment by MeanderingProgrammer** [comment]
There was not a way to do this before. I think disabling rendering in diff mode makes sense in general so I made it the new default behavior: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/01b38dcf7d0a99620547651fb59a3ba521ba12d5.

Please update the plugin and LMK if it works!
