### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by pienter-tech** [MeanderingProgrammer/render-markdown.nvim#170]
### Neovim version (nvim -v)

0.10.1

### Operating system

MacOs

### Terminal emulator / GUI

WezTerm

### Describe the bug

Bold and Italic not rendered correctly when using underscore and ending with a number.

See example below:

`__1212a__ __1212__ **1212**`
<img width="298" alt="Screenshot 2024-09-18 at 10 39 10" src="https://github.com/user-attachments/assets/f9171172-8843-4c68-8804-0ffec6ed289a">

<img width="233" alt="Screenshot 2024-09-18 at 10 39 02" src="https://github.com/user-attachments/assets/9faf5b76-0ead-42db-81a7-2cb6926fc310">

Notice the `__1212__` is not concealed.

### Expected behavior

I would expect the Bold and Italic text to be rendered the same as when using *

### Healthcheck output

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.0.9
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled

render-markdown.nvim [executables] ~
- OK none to check

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: installed but should not conflict

### Plugin configuration

 ``` lua
{
        "MeanderingProgrammer/render-markdown.nvim",
        opts = {
            latex = { enabled = false },
            heading = {
                enabled = true,
                sign = true,
                position = "overlay",
                icons = {
                    "◈ ",
                    "◇◇ ",
                    "◆◆◆ ",
                    "⋄⋄⋄⋄ ",
                    "❖❖❖❖❖ ",
                    "⟡⟡⟡⟡⟡⟡⟡  ",
                },
                signs = { "󰫎 " },
                width = "full",
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = true,
                border_prefix = false,
                above = " ",
                below = " ",
                backgrounds = {
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                },
                foregrounds = {
                    "RenderMarkdownH1",
                    "RenderMarkdownH2",
                    "RenderMarkdownH3",
                    "RenderMarkdownH4",
                    "RenderMarkdownH5",
                    "RenderMarkdownH6",
                },
            },
            indent = {
                enabled = true,
                per_level = 2,
            },
            bullet = {
                enabled = true,
                icons = { "○", "●", "◆", "◇" },
                left_pad = 0,
                right_pad = 0,
                highlight = "RenderMarkdownBullet",
            },
        },
        dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.icons" },
    },
```

### Plugin error log

N/A

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
This comes down to the parser. I don't know exactly why but when using underscores the element is recognized as only a `paragraph` whereas when you add a letter it gets correctly identified as a `strong_emphasis`. You can use `:InspectTree` to see what gets identified as a `strong_emphasis` vs not.

Unsure if this is a bug or if underscores with numbers define some other markdown block. May be worth cutting an issue to the `markdown` parser.

**Comment by MeanderingProgrammer** [comment]
Appears to be a known issue that emphasis does not always work as intended.

I've updated this issue with an example: https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/8.
