### ISSUE TITLE
help: no highlight for headings and code blocks for quarto `qmd` file

### ISSUE THREAD

**Issue by hopezh** [MeanderingProgrammer/render-markdown.nvim#174]
### Description

As shown below, render-markdown doesn't seem to recognize `qmd` file from `quarto`, even though I added `file_types = {"markdown", "quarto"}` in the config.

May I ask if I missed any critical steps here? (This is a fresh installation of the latest lazyvim, and quarto CLI, quarto-nvim, and marksman LSP have all being installed)

My nvim config based on `lazyvim`:  [oatvim08](https://github.com/hopezh/oatvim08)

1. no highlight for headings and code block for `.qmd` files:
<img width="1443" alt="Screenshot 2024-09-20 at 10 29 38 PM" src="https://github.com/user-attachments/assets/325c3291-cb2b-4079-a6ef-5efa40b71ac3">

2. correct highlights for the same file in `.md` format:
<img width="1443" alt="Screenshot 2024-09-20 at 10 30 02 PM" src="https://github.com/user-attachments/assets/cdf48071-8340-4eaa-bdf6-a271a15aca4f">

3. my config for `render-markdown.nvim`:
<img width="1443" alt="Screenshot 2024-09-20 at 10 31 04 PM" src="https://github.com/user-attachments/assets/5ecb2a02-a0eb-433d-a69b-74c113e4013d">

4. My `LspInfo` in nvim:
<img width="1313" alt="Screenshot 2024-09-20 at 10 43 47 PM" src="https://github.com/user-attachments/assets/613a6bca-cbd7-4f11-91ca-516d3c99095d">

**Comment by MeanderingProgrammer** [comment]
Hmm, I'm curious what changed after: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/76?

**Comment by MeanderingProgrammer** [comment]
You might be able to fix this by registering `markdown` as the parser for `quatro` files:

```lua
vim.treesitter.language.register('markdown', 'quarto')
```

**Comment by hopezh** [comment]
Thanks, @MeanderingProgrammer 

I tried to add the line you suggested in the config file for `nvim-treesitter`, as shown below:
 
<img width="1425" alt="Screenshot 2024-09-21 at 10 52 40 PM" src="https://github.com/user-attachments/assets/28679df3-e418-4685-90e7-863ca55fbee7">

However, the only difference in the `qmd` file that I notice is the symbols for the level 2 and 3 headings change to the one looks like two overlapping S, and there is no background color for code block: 

<img width="1425" alt="Screenshot 2024-09-21 at 10 53 09 PM" src="https://github.com/user-attachments/assets/ad355419-eea0-44e2-a958-f906dc30c72d">

**Comment by MeanderingProgrammer** [comment]
I'm not sure if putting the `vim.treesitter.language.register('markdown', 'quarto')` line in the `setup` function will cause any problems but in either case it definitely shouldn't be in there.

**Comment by MeanderingProgrammer** [comment]
I've been able to make this work without registering `markdown` as the parser and using `quarto-nvim` seems to have no impact on this plugin. 

I'm not sure if something is out of date or a plugin that I can't seem to find is causing problems on your end but at this point I need a minimal reproducible example to figure out what's interfering.

Here's a starting point:

```lua
-- Add any other options needed to cause the problem here
vim.opt.number = true
vim.opt.relativenumber = true

-- Basic lazy.nvim setup
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.uv.fs_stat(lazypath) then
    local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
    vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    -- Feel free to use another colorscheme
    {
        'folke/tokyonight.nvim',
        config = function()
            ---@diagnostic disable-next-line: missing-fields
            require('tokyonight').setup({ style = 'night' })
            vim.cmd.colorscheme('tokyonight')
        end,
    },
    -- This part is needed to enable highlighting for treesitter
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        config = function()
            ---@diagnostic disable-next-line: missing-fields
            require('nvim-treesitter.configs').setup({
                ensure_installed = { 'markdown', 'markdown_inline' },
                highlight = { enable = true },
            })
        end,
    },
    {
        'MeanderingProgrammer/render-markdown.nvim',
        dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' },
        config = function()
            require('render-markdown').setup({
                file_types = { 'markdown', 'quarto' },
            })
        end,
    },
})
```

Save this to `minit.lua` and open the file with `nvim -u minit.lua test.qmd`.

Add to the `minit.lua` file until you can re-create the problem.

**Comment by hopezh** [comment]
Thanks, @MeanderingProgrammer 

I tried installing a fresh `lazyvim` and adding plugins one at a time to find out at which step `render-markdown` stops working for `qmd` file. 

It seems after installing the `lazyvim extras` for `markdown`, this issue will occur: `render-markdown` is no longer able to highlight markdown components in `qmd` file as it is expected to.

The issue goes away after unintalling the `lazyvim extras for markdown`.

I'm not sure which plugins in this `extras` package is causing the issue. But for now, I'll stay away from it.

Hope this helps. 

<img width="1545" alt="Screenshot 2024-09-25 at 11 11 49 PM" src="https://github.com/user-attachments/assets/0c96f5da-25de-4ca8-a64d-10f676132a0e">

**Comment by MeanderingProgrammer** [comment]
Ahh, this might be an issue with `LazyVim` overriding your settings, since this plugin is part of the markdown extras. This is something to be aware of for all plugins that are shared between your config and `LazyVim`.

I believe to change the settings of a plugin already in `LazyVim` you need to use `opts` rather than a config function.

I added a new command to help debug configuration settings here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/a9643f4377f39f4abf943fbc73be69f33f5f2f1d

If you update the plugin then run `:RenderMarkdown config` you should see `quarto` in the output for `file_types`. If not its most likely `LazyVim` overriding your settings.

To fix this I believe you would need to do something like:

```lua
{
    'MeanderingProgrammer/render-markdown.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' },
    opts = {
        file_types = { 'markdown', 'quarto' },
        code = { above = '', below = '' },
    },
}
```

**Comment by matthewblott** [comment]
I don't know if this is related but I also have an issue with the code blocks. Everything renders as expected but the triple backticks followed by the language name aren't hidden when the icon is visible:

![Screenshot 2024-09-28 at 13 08 36](https://github.com/user-attachments/assets/188edbef-5190-4510-a35e-d4021ccd421e)

**Comment by MeanderingProgrammer** [comment]
That problem gets caught by the health check
