### ISSUE TITLE
bug: padding color not aligned with floating win bg color when `code.width == 'block'`

### ISSUE THREAD

**Issue by Bekaboo** [MeanderingProgrammer/render-markdown.nvim#176]
### Neovim version (nvim -v)

0.10.0

### Operating system

Linux

### Terminal emulator / GUI

Alacritty

### Describe the bug

When rendering markdown in LSP floating windows, if `code.width` is set to `block`, the paddings after the code blocks use normal bg color instead of the bg color of the floating window.

![image](https://github.com/user-attachments/assets/5d8e7cc6-0f3a-415f-95cd-05f59546352e)

### Expected behavior

Paddings after the code blocks should have the same color as the floating window.

### Healthcheck output

```
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.1.1
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- ERROR render-markdown.signs: is not a valid key

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

```

### Plugin configuration

```lua
require('render-markdown').setup({
  code = {
    sign = false,
    width = 'block',
    position = 'right',
    language_pad = 2,
    left_pad = 2,
    right_pad = 2,
    border = 'thick',
    above = ' ',
    below = ' ',
    highlight_inline = 'RenderMarkdownCodeInline',
  },
})
```

### Plugin error log

N/A

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Should be fixed after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/095078d931ce23b544face8ca7b845adf7fad7e9

Give it a shot!

**Comment by Bekaboo** [comment]
Wow that's fast! Thanks for the quick fix.
