### ISSUE TITLE
bug: Telescope causing rendering to glitch?

### ISSUE THREAD

**Issue by sohanglal** [MeanderingProgrammer/render-markdown.nvim#177]
### Neovim version (nvim -v)

0.10.1

### Operating system

NixOS

### Terminal emulator / GUI

kitty

### Describe the bug

When I open telescope the rendering in the backgroud reverts back to raw form. When I close telescope and return back to the buffer the rendering is perfect. This isn't the issue 
The issue arises when: 
1. I open telescope 
2. Navigate to another file using telescope 
3. press `c-6` to access the alternate buffer, the alternate buffer is in the raw rendering 

Here is an example:
Open test.md 
![image](https://github.com/user-attachments/assets/a20eb600-27c3-4e76-87a0-739368474df7)
Open telescope. Rendering broken in the background. Not an issue 
![image](https://github.com/user-attachments/assets/ba044528-3db9-480a-80d8-3d8b777ad42e)
Navigate to test2.md using telescope. Rendering is perfect.
![image](https://github.com/user-attachments/assets/98e8f77b-feb7-4dc1-a1cf-7fb198e38e2f)
Navigate back to test.md using `c-6` the shortcut for the alternate buffer and the rendering is broken
![image](https://github.com/user-attachments/assets/07395ecf-4bf3-4ae3-be7c-ff65bf2358cb)
Rendering can be reset by cycling to the insert mode and then normal mode back again

### Expected behavior

The alternate buffer should render markdown perfectly

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.1.3
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

  {
      'MeanderingProgrammer/render-markdown.nvim',
      opts = {},
      dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' }, -- if you use the mini.nvim suite
            render_modes = { 'n', 'v', 'i', 'c' },
      -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
      -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
  },

### Plugin error log

N/A

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
> When I open telescope the rendering in the backgroud reverts back to raw form. When I close telescope and return back to the buffer the rendering is perfect.

I know you said this isn't the issue but if you set `render_modes = { 'n', 'v', 'i', 'c' },` it shouldn't occur.
The issue here is that you're setting `render_modes` on the `lazy.nvim` config and not in the `opts` for this plugin.
Unsure if that's intentional but nesting `render_modes` in `opts` will fix this problem:

```lua
opts = {
  render_modes = { 'n', 'v', 'i', 'c' },
},
``

**Comment by MeanderingProgrammer** [comment]
The alternate  buffer rendering should be fixed after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/f187721a5381f4443ef97ad1a7c0681a65511d28

**Comment by sohanglal** [comment]
> > When I open telescope the rendering in the backgroud reverts back to raw form. When I close telescope and return back to the buffer the rendering is perfect.
> 
> I know you said this isn't the issue but if you set `render_modes = { 'n', 'v', 'i', 'c' },` it shouldn't occur. The issue here is that you're setting `render_modes` on the `lazy.nvim` config and not in the `opts` for this plugin. Unsure if that's intentional but nesting `render_modes` in `opts` will fix this problem:
> 
> ```lua
> opts = {
>   render_modes = { 'n', 'v', 'i', 'c' },
> },
> ```

My bad, I was wondering why the rendering wasn't working in the other modes. Thanks for pointing it out




> The alternate buffer rendering should be fixed after: [f187721](https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/f187721a5381f4443ef97ad1a7c0681a65511d28)

Works like a charm! Thanks for this is amazing plugin
