### ISSUE TITLE
bug: Heading icons not rendered

### ISSUE THREAD

**Issue by paulwyszynski** [MeanderingProgrammer/render-markdown.nvim#178]
### Neovim version (nvim -v)

0.10.1

### Operating system

MacOS

### Terminal emulator / GUI

Kitty

### Describe the bug

Hi ,

any ideas why the heading icons are not visible? Occured since last update I guess through lazy.

![Screenshot 2024-09-22 at 11 41 38 PM](https://github.com/user-attachments/assets/f5d3cf40-932a-4c8f-9554-36d5e1c21eec)

### Expected behavior

Headings icons 1, 2, 3, 4, etc.

### Healthcheck output

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.1.3
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

```
return {
  "MeanderingProgrammer/markdown.nvim",
  opts = {
    heading = {
      -- Turn on / off heading icon & background rendering
      enabled = true,
      -- Turn on / off any sign column related rendering
      sign = true,
      -- Replaces '#+' of 'atx_h._marker'
      -- The number of '#' in the heading determines the 'level'
      -- The 'level' is used to index into the array using a cycle
      -- The result is left padded with spaces to hide any additional '#'
      icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
      -- Added to the sign column if enabled
      -- The 'level' is used to index into the array using a cycle
      signs = { "󰫎 " },
      -- The 'level' is used to index into the array using a clamp
      -- Highlight for the heading icon and extends through the entire line
      backgrounds = {
        "RenderMarkdownH1Bg",
        "RenderMarkdownH2Bg",
        "RenderMarkdownH3Bg",
        "RenderMarkdownH4Bg",
        "RenderMarkdownH5Bg",
        "RenderMarkdownH6Bg",
      },
      -- The 'level' is used to index into the array using a clamp
      -- Highlight for the heading and sign icons
      foregrounds = {
        "RenderMarkdownH1",
        "RenderMarkdownH2",
        "RenderMarkdownH3",
        "RenderMarkdownH4",
        "RenderMarkdownH5",
        "RenderMarkdownH6",
      },
    },
  },
  -- dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
  dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.icons" }, -- if you use standalone mini plugins
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
}

```

### Plugin error log

N/A

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Do you use LazyVim?

If so update the name of the plugin to reflect the new repository name:

- `MeanderingProgrammer/markdown.nvim` -> `MeanderingProgrammer/render-markdown.nvim`

Might be an issue of joining configs when the plugin name mismatches, but that's just a guess.

**Comment by paulwyszynski** [comment]
Oh yes, that was the issue. Thx I did not change the name in my own config 🙈

**Comment by spwx** [comment]
Looks like LazyVim has updated the name of the plugin to `render-markdown.nvim`. However it's changing the default config. I'm using this to reset:

```lua
{
    "MeanderingProgrammer/render-markdown.nvim",
    opts = {
      -- Mimic org-indent-mode behavior by indenting everything under a heading based on the
      -- level of the heading. Indenting starts from level 2 headings onward.
      indent = {
        -- Turn on / off org-indent-mode
        enabled = true,
        -- Amount of additional padding added for each heading level
        per_level = 2,
        -- Heading levels <= this value will not be indented
        -- Use 0 to begin indenting from the very first level
        skip_level = 1,
        -- Do not indent heading titles, only the body
        skip_heading = false,
      },
      sign = {
        -- Turn on / off sign rendering
        enabled = true,
        -- Applies to background of sign text
        highlight = "RenderMarkdownSign",
      },
      code = {
        sign = true,
        width = "block",
        right_pad = 1,
      },
      heading = {
        sign = true,
        icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
      },
    },
  }
```

**Comment by paulwyszynski** [comment]
Yeah thanks, I did not update my own merge config for this, so the render- was missing in the dependency name of my markdown.lua
