### ISSUE TITLE
feature: Indent top-level unordered  ("bulleted") list items

### ISSUE THREAD

**Issue by proofer** [MeanderingProgrammer/render-markdown.nvim#181]
### Is your feature request related to a problem? Please describe.

Unordered list items, e.g.,  
```
| <-- left margin, if this were not a github markdown code block in order to render literal hyphens
- first item  
- second item
```
should be rendered indented, should't they?

### Describe the solution you'd like

- first item
- second item

--Using github's markdown rendering to show what I'd like; the pre-rendering hyphens are at the left margin

### Describe alternatives you've considered

I don't know what other solutions or features to consider, given that I otherwise like render-markdown.nvim a lot.

**Comment by proofer** [comment]
This works
```
    opts = {
        bullet = {
            left_pad = 4,
        },
    },
```
except the wrapped portion of  line-wrapped list items now doesn't indent nicely.

**Comment by MeanderingProgrammer** [comment]
No worries, the configuration for this plugin is not easy to parse though. In general most components should support padding in some for or another.

Applying padding to all lines of list items should work after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/3adb9d539a016bc63fee83aa740e38fa4eeab094.

**Comment by proofer** [comment]
I updated with Lazy and its log now shows 3adb9d5 as the latest commit. I closed and re-opened an .md file that exhibited the wrap issue, but see no change. Is there something else I should do?
<img width="815" alt="image" src="https://github.com/user-attachments/assets/bff82320-3558-4f7d-a303-f224fd68bafe">

**Comment by proofer** [comment]
I should add that the instances I am seeing are not really dynamically wrapped but are multiple-line items. However, the issue does occur with dynamically-wrapped items, e.g., when resizing a window.

**Comment by MeanderingProgrammer** [comment]
Ah I thought you were referring to manual line breaks in markdown files, but you're taking about actual line breaks.

That's not something I can control in the plugin and is completely up to your neovim config for how line breaks are handled. Checkout:

- `:help 'showbreak'`
- `:help 'breakindent'`
- `:help 'breakindentopt'`

Likely what you want is for me to be able to add padding to line breaks equal to the added padding around the bullet point.

Unfortunately this is basically impossible.

**Comment by proofer** [comment]
I *think* that what I called dynamically wrapped you call actually wrapped -- your suggested `:help` references are about those; I understand that you can't handle those.  And due undoubtedly to some operator error, while the image I posted above was indeed made after updating and closing-re-opening the .md file, now that I've closed-re-opened again I see that the pictured list items are handled perfectly.
<img width="814" alt="image" src="https://github.com/user-attachments/assets/ad17de63-e863-49e6-a4f3-af6e00f600d1">
So in the end I'm  glad a made small contribution the the plugin by posting the issue :)

**Comment by MeanderingProgrammer** [comment]
Ah gotcha, I wasn't sure how to describe the difference, maybe manually wrapped?

Anyway, glad we were on the same page and the fix works for you! I imagine there can be many reasons for an update not being picked up immediately.

I agree the new behavior is a much better way to handle padding list items. I think this might be a remanent from when I only handled the literal bullet point of list items.

Thanks for brining up the issue!
