### ISSUE TITLE
feature: support an array of values for heading.min_width

### ISSUE THREAD

**Issue by hneutr** [MeanderingProgrammer/render-markdown.nvim#182]
### Is your feature request related to a problem? Please describe.

I'd love to have varying levels of `min_width` depending on the header level. An example config:

```
require('render-markdown').setup({
    heading = {
        enabled = true,
        width = {'full', 'block', 'block'},
        min_width = {-1, 60, 40},
    },
})
```

### Describe the solution you'd like

Behavior similar to `heading.width`, ie support both cycle and clamp behavior for the arrays.

### Describe alternatives you've considered

Interpret numbers in the `header.width` field as `min_width`. An example config:

```
require('render-markdown').setup({
    heading = {
        enabled = true,
        width = {'full', 60, 40},
    },
})
```

### Additional information

This plugin is awesome. I really appreciate all the work you've put into it!

**Comment by MeanderingProgrammer** [comment]
Sure, added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/aad1a1220dc9da5757e3af3befbc7fc3869dd334

Added it to a variety of other options as well: `left_margin`, `left_pad`, `right_pad`, and `min_width` all support arrays now.

**Comment by hneutr** [comment]
Dude — you are awesome, thank you, for both this and #183.
