### ISSUE TITLE
feature: make behavior when `header.border = true` consistent whether or not there is a blank newline above/below the header

### ISSUE THREAD

**Issue by hneutr** [MeanderingProgrammer/render-markdown.nvim#183]
### Is your feature request related to a problem? Please describe.

Currently, when `header.border = true` and there is a blank newline above the header, the border is applied to the blank newline, but when there is a non-blank line above the header, a "phantom" line is rendered and the border is applied to that "phantom" newline, and this behavior is the same for the border below the header. 

This makes moving up or down by line when there is a header unpredictable. To make the situation a bit clearer:

The following would look the same:
```
text [cursor]

# header
```

```
text [cursor]
# header
```

However, moving the cursor down a line in the first example would move the cursor to the empty line (and hide the border of the header), while moving the cursor down in the second example would move the cursor to the line with the header.

### Describe the solution you'd like

When `header.border = true`, render the border on a "phantom" line, regardless of whether or not there is an empty line above or below it.

This would have the added benefit of fixing the rendering headers at the top and bottom of the file (currently, when there is a header at the top of the file, the top border is not rendered, and the same is true of the bottom border for a header on the last line of the file).

### Describe alternatives you've considered

Add a configuration value to control this behavior, eg: `header.border_position`, with (perhaps) a value of `overlay` preserving the current behavior, and a value of `virtual` (or some better-named value) triggering the consistent behavior I've described above.

### Additional information

Again, I really appreciate this plugin and all of the work you've put into it! It's meaningfully improved my Neovim experience.

**Comment by MeanderingProgrammer** [comment]
The top and bottom lines don't get fixed by rendering a virtual line on them. 

Under the current implementation there's already a virtual line being rendered in both places: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/123#issuecomment-2274588879

You can see the top one if you hit `<C-b>`.

**Comment by MeanderingProgrammer** [comment]
I can add an opt in to make the lines always virtual.

**Comment by MeanderingProgrammer** [comment]
Added this here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/aad1a1220dc9da5757e3af3befbc7fc3869dd334.

You can opt into it by setting `heading.border_virtual` to `true`.
