### ISSUE TITLE
bug: Visual effects cleared when markdown files is splitted and scrolled

### ISSUE THREAD

**Issue by Bekaboo** [MeanderingProgrammer/render-markdown.nvim#184]
### Neovim version (nvim -v)

0.10.0

### Neovim distribution

N/A

### Operating system

Linux

### Terminal emulator / GUI

Alacritty

### Describe the bug

When a markdown file is splitted into two windows and one of the window scrolls, the visual effects can be cleared in another window.

### Expected behavior

Both windows render normally.

### Healthcheck output

```
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.1.11
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- ERROR render-markdown.signs: is not a valid key

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
require('render-markdown').setup()
```

### Plugin error log

N/A

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

### Additional information

I believe this is because render-markdown clears "off-screen" extmarks but it only considers visible range of the file in the current window instead of all windows that contain the markdown file.

A video that demonstrate the bug (observe the split on the left):

https://github.com/user-attachments/assets/9a142a4e-f654-4f32-a291-8e1f6e5cc860

**Comment by MeanderingProgrammer** [comment]
I'm curious what is the reason to open the same markown file in multiple windows?

**Comment by MeanderingProgrammer** [comment]
Your assumption is correct, we only render within the visible range + some buffer of a file. The range will be determined by the active window.

**Comment by Bekaboo** [comment]
> I'm curious what is the reason to open the same markown file in multiple windows?

Taking notes while referencing to the previous section of the note? There are many use cases actually. I often find myself using splits to view different parts of the same file simultaneously to have a grasp of the whole file structure.

**Comment by MeanderingProgrammer** [comment]
Yeah, I do that with code, but I was just wondering when that would happen with markdown. I guess my use of it doesn't often involve looking at different parts, but it sounds reasonable. This one might take some time.

**Comment by cideM** [comment]
Just chiming in to say that I split and scroll a lot as well and therefore this issue is quite important to me

**Comment by MeanderingProgrammer** [comment]
Turned out not too difficult. I thought the visible range logic might have leaked to multiple places, but nope, fairly contained.

Should work after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/767707e928389996e8860f03552cf962afb0bfb2.

**Comment by Bekaboo** [comment]
Thanks! Closing this as fixed.
