### ISSUE TITLE
bug: incorrect rendering when `header.border = true` and `vim.opt.wrap = true`

### ISSUE THREAD

**Issue by hneutr** [MeanderingProgrammer/render-markdown.nvim#187]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

N/A

### Operating system

MacOs

### Terminal emulator / GUI

kitty

### Describe the bug

When `heading.boarder = true` and part of a wrapped line is offscreen, but has been onscreen before, rendering is shifted down from its expected location.

1. set `vim.opt.wrap = true`
2. make a line that takes up more than half the screen (so if there are `Y = vim.o.lines - vim.o.cmdheight` vertical lines and `X = vim.opt.columns` (minus however wide the signcolumn/etc is) columns, make a line of at least `(X+1) * (Y+1)` characters long)
3. yank the long line
4. add a new line with `# ` on it
5. add a new line and paste the long line on it

This will result in the rendering being applied below the expected location. If you close the file, you can replicate the bug by moving to the top and then bottom of the file, and then moving to the header.

Here's a visual representation, with `X` representing the long line and `|` representing the line the cursor is on (cursor column doesn't matter):

add the long line:

```
X|
```

add the header:

```
X
#|
```

add a second long line below the header:

```
X
#
X|
```

Here's a screenshot of the end state:
<img width="1728" alt="rendered content" src="https://github.com/user-attachments/assets/0a091544-054e-48ba-a695-e85067780877">

and here's a screenshot of the text after running `:RenderMarkdown disable`:
<img width="1728" alt="text content after disabling the plugin" src="https://github.com/user-attachments/assets/d46770a3-0ff2-4aa7-8131-3f9440a82ffb">

### Expected behavior

Rendering of text happens on the line with the text.

### Healthcheck output

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.2.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- ERROR render-markdown.code.position: expected one of { "left", "right" }, got 

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

require('render-markdown').setup({
    heading = {
        border = true,
    },
})

### Plugin error log

N/A

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
I am unable to replicate this behavior:

| Before Paste | After Paste |
| --- | --- |
| ![before-paste](https://github.com/user-attachments/assets/cfa78154-f517-4823-b1b2-eb731b42a0b9) | ![after-paste](https://github.com/user-attachments/assets/1dc0d67e-c6ec-4823-acc6-241c67c9c0e2) |

In either case if this behavior relies on someone having a line that conservatively is:

- width = 100
- height =40
- line length = 4,000

So a 4000 character long line, is not something I'm going to bother to support.

**Comment by MeanderingProgrammer** [comment]
Do let me know if this is an actual situation you ran into though, or like a pushing the bounds of the plugin kind of thing.

**Comment by hneutr** [comment]
Ah, sorry, yes, this is an actual issue I have — the intention behind the very specific and weird  example was to give you a reproducible example — I'll try and get you one without any settings, from as minimal a vimrc as I can get. 

Some context on when this is happening: I write markdown files in a buffer with the zen-mode plugin, so my buffer width is 80, and the lines are frequently long — they don't have to be particularly long to trigger the bug for me, just long enough to cause them to wrap off screen.

**Comment by hneutr** [comment]
Great! I'll try and get an example working with that config. Thank you!

**Comment by hneutr** [comment]
Ah, your instinct was correct! The bug only shows up when `vim.wo.smoothscroll = true`.

**Comment by hneutr** [comment]
I'll report an issue and close this one — I appreciate your work here, as always!

**Comment by hneutr** [comment]
Here's the issue, if you have context to add https://github.com/neovim/neovim/issues/30603#issue-2558077415

**Comment by MeanderingProgrammer** [comment]
Thanks for creating that, incredibly fast turn around, `0.10.2` seems to work!
