### ISSUE TITLE
help: How do I enable rendering for visual-block mode?

### ISSUE THREAD

**Issue by einarpersson** [MeanderingProgrammer/render-markdown.nvim#188]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

N/A

### Description

I have successfully switched on rendering for all modes, including visual-block which is not covered in the [wiki](https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki#render-modes). However, I cannot do it for visual block. How should I do it (or is it not supported yet?)?

**Comment by MeanderingProgrammer** [comment]
I updated the `render_modes` description to hopefully be more helpful: https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki#render-modes.

If you want rendering in all modes you can set `render_modes` to `true`:

```lua
require('render-markdown').setup({
  render_modes = true,
})
```

To just add visual block mode you need to add the string value of the mode to the list, CTRL-V, which in lua is represented by its ascii value, 22:

```lua
require('render-markdown').setup({
  render_modes = { ...,  '\22' },
})
```
