### ISSUE TITLE
feature: Request for Support for Wiki-style Links

### ISSUE THREAD

**Issue by BeltranLeo** [MeanderingProgrammer/render-markdown.nvim#190]
### Is your feature request related to a problem? Please describe.

Hello,

I am currently using the MeanderingProgrammer/render-markdown.nvim plugin for rendering Markdown in Neovim, and I would like to request the addition of support for wiki-style links (e.g., `[[Link|Alias]]`). This feature would greatly enhance compatibility with the Obsidian plugin.

Currently, the plugin renders `[[Link|Alias]]` as `[Link|Alias]`, which does not provide the intended functionality of creating a clickable link with an alias. Adding support for this format would enhance the overall user experience.

### Benefits:

1. **Better integration with Obsidian:** This would allow users who utilize both plugins to work more seamlessly.
2. **Improved usability:** Wiki-style links are intuitive and can enhance note navigation.

### Describe the solution you'd like

I would like the following formats to be supported:

- **Basic link:**  

```
[[Link]]
```

- **Link with alias:**  

```
[[Link|Alias]]
```

The first format should render as a link to `Link`, while the second format should display `Alias` as the clickable text but link to "Link."

### Describe alternatives you've considered

I have explored a few alternatives to achieve the expected functionality, but unfortunately, they did not work as intended:

1. **Using Markdown Extensions:**  I looked into using Markdown extensions that support wiki-style links, but they were not compatible with the current setup of MeanderingProgrammer/render-markdown.nvim, leading to rendering issues.

2. **Manual Link Creation:** I tried manually creating links using the standard Markdown format, like `[Alias](Link)`, but this does not replicate the ease of use and familiarity of the wiki-style links that Obsidian users expect.

Each of these approaches fell short of providing the desired integration and functionality, highlighting the need for native support for wiki-style links in the plugin.

**Comment by MeanderingProgrammer** [comment]
I'm unsure what version of this plugin you're using or if there's some bug going on, but this plugin already supports wiki links, both with and without aliases, and renders them like you describe.

**Comment by BeltranLeo** [comment]
I’m currently running the last commit and using the default configuration:

![image](https://github.com/user-attachments/assets/f1195346-3c64-4b5d-8b8f-16a847dd4420)

**Comment by MeanderingProgrammer** [comment]
Can you run `:checkhealth render-markdown`, I have a feeling there's a conflict and that should catch it

**Comment by BeltranLeo** [comment]
You were right. I was running an old version of Neovim (0.9) without realizing it. Updated to 0.10.1 and now it works as expected.

![image](https://github.com/user-attachments/assets/c16d90d0-f70d-400c-8e7c-2e8de1c2213e)

**Comment by MeanderingProgrammer** [comment]
Awesome!
