### ISSUE TITLE
bug: Indented tables do not view correctly

### ISSUE THREAD

**Issue by MinaMatta98** [MeanderingProgrammer/render-markdown.nvim#191]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

LazyVim

### Operating system

Arch x86_64

### Terminal emulator / GUI

Alacritty/Kitty

### Describe the bug

When tables are indented, the top and bottom borders are omitted:

![image](https://github.com/user-attachments/assets/e04952f5-1d4b-4080-b033-5286d200d129)

### Expected behavior

It should show the border

### Healthcheck output

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.2.6
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

return {
	"MeanderingProgrammer/render-markdown.nvim",
	opts = {},
	dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
	-- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
	-- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
}

### Plugin error log

None

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Fixed here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/efb4c48c3b4de7cc3d01ec54d794a2509ae0c1c8

**Comment by MinaMatta98** [comment]
Can confirm fixed :).

Thank you!
