### ISSUE TITLE
feature: support `icon` on individual callouts

### ISSUE THREAD

**Issue by hneutr** [MeanderingProgrammer/render-markdown.nvim#194]
### Is your feature request related to a problem? Please describe.

Callouts are great for leveraging the plugin to apply custom highlights. It would be amazing if individual callouts could specify their own `icon` parameter, overwriting the one specified in `config.quote.icon`. This is definitely a minor feature request!

### Describe the solution you'd like

Allow callouts to overwrite the `icon` parameter set in the `config.quote.icon`.

### Describe alternatives you've considered

In my particular use-case, I don't actually want an icon on some callouts. So, an alternative would be allowing callouts to specify that no icon be rendered. Since this can be achieved with `quote.icon = ''`, this doesn't feel like a particularly good solution, but it would work.

### Additional information

As always, I appreciate the time and effort you put into this plugin — it has genuinely improved my day to day experience with Neovim.

**Comment by MeanderingProgrammer** [comment]
Added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/1eb3b74873d2dbb9d5a3635bf4a14e77e897d29f.

For each callout you can now specify a `quote_icon` value.

If you want no icon to be rendered I would use a space, i.e. `quote_icon = ' '`, rather than the empty string.
