### ISSUE TITLE
bug: Checkbox custom todo

### ISSUE THREAD

**Issue by gmcusaro** [MeanderingProgrammer/render-markdown.nvim#196]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

N/A

### Operating system

MacOS

### Terminal emulator / GUI

Alacritty

### Describe the bug

In checkbox, my todo customization is not applied. In addition `enabled = false` should already disable all rendered

https://github.com/user-attachments/assets/e96708ab-002d-451d-adfc-1b20b5fae4ae

### Expected behavior

Remove default todo behaviour

### Healthcheck output

```text
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.2.9
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
checkbox = {
    enabled = false,
    custom = {
        todo = { raw = '', rendered = '', highlight = '' },
    },
}
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

### Additional information

I also tried this setup `todo = { raw = '[-]', rendered = '[-]', highlight = '' }` with same problem

**Comment by MeanderingProgrammer** [comment]
Disabling checkboxes does work here, though what you want that to mean and what it actually means might differ.

So when checkboxes are disabled we no longer apply the `todo` icon and we don't remove the bullet point at the start. However the syntax `[-]` is a special type of treesitter node in markdown called a `shortcut_link`. The default highlighting in `nvim-treesitter` conceals the square brackets around the `shortcut_link`: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown_inline/highlights.scm#L80.

So when checkboxes are disabled all you see is the effect of the default conceal behavior which hides the square brackets.

You can disable concealing in general but that will have all sorts of effects on other rendering behavior.

What exactly is it you're trying to accomplish? As soon as you set `enabled = false` nothing you put in `custom` will have any effect. When enabled is false all of the rendering behavior around checkboxes is disabled. 

Here are 2 different approaches to disable the `todo` behavior:


```lua
checkbox = {
    custom = { todo = { raw = '[SOME_VALUE_I_WILL_NEVER_USE]' } },
}
```

```lua
checkbox = {
    custom = { todo = { rendered = '[-]' } },
}
```

Again the only thing you can't disable without effecting a lot of other things is concealing the square brackets.
