### ISSUE TITLE
help: Set sign colours manually

### ISSUE THREAD

**Issue by SebastianMusic** [MeanderingProgrammer/render-markdown.nvim#197]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

N/A

### Description

I am using the [nvim gruvbox theme](https://github.com/ellisonleao/gruvbox.nvim) it did not support heading colours with render-markdown.nvim so after some time i figured out how to make my own colours.
This is now inside of my gruvbox theme
```lua
overrides = {
      RenderMarkdownH1Bg = { fg = '#fb4934', bg = '', bold = true },
      RenderMarkdownH2Bg = { fg = '#fabd2f', bg = '', bold = true },
      RenderMarkdownH3Bg = { fg = '#b8bb26', bg = '', bold = true },
      RenderMarkdownH4Bg = { fg = '#8ec07c', bg = '', bold = true },
      RenderMarkdownH5Bg = { fg = '#83a598', bg = '', bold = true },
      RenderMarkdownH6Bg = { fg = '#d3869b', bg = '', bold = true },
    },
```
The only issue is that i can't find the parameter-name of the signs, since they too do not follow the gruvbox theme, so i would like to manually just set them to the correct colours the way i did with the markdown headings.

So the question is how do i manually change the colours for the different signs?

**Comment by MeanderingProgrammer** [comment]
All the highlight information is defined here: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#colors.

Sign highlights are not specified explicitly but in general use the foreground color of the associated object, in this case the heading.

The various `HnBg` are meant to supply a background color rather than a foreground.

Try modifying your overrides to:

```lua
overrides = {
      RenderMarkdownH1 = { fg = '#fb4934', bg = '', bold = true },
      RenderMarkdownH2 = { fg = '#fabd2f', bg = '', bold = true },
      RenderMarkdownH3 = { fg = '#b8bb26', bg = '', bold = true },
      RenderMarkdownH4 = { fg = '#8ec07c', bg = '', bold = true },
      RenderMarkdownH5 = { fg = '#83a598', bg = '', bold = true },
      RenderMarkdownH6 = { fg = '#d3869b', bg = '', bold = true },
},
```

**Comment by SebastianMusic** [comment]
Thank you that worked a lot better. This removed other issues that came from my "fix" as well.

I am both new to neovim and computer science (I started my first year in computer science this august) so i did not know that i could change treesitter like this. So again thank you for your speedy reply.

When i used your solution though i got some wierd green overlay on every heading. I had to add empty '' strings inside of the backgrounds in my render-markdown.lua file, and then that problem vanished. Thank you very much again.
<img width="447" alt="image" src="https://github.com/user-attachments/assets/741b0df9-971e-4559-9e2b-79c94e520792">

**Comment by MeanderingProgrammer** [comment]
No problem, and super cool that you're taking an interest in stuff like this so early on.

I would say though that you're not "changing treesitter". The world of highlighting things is to the best of my knowledge a bit loosey goosey. 

Treesitter in general is a way to parse languages.

Then on top of that `nvim-treesitter` assigns common names to different patterns for each language, i.e. variables get assigned to `@variable` regardless of the language. You can see the full list in `:h treesitter-highlight-groups`.

Then color schemes implement concrete colors for these common names and voila you get syntax highlighting.

But not all color schemes implement all of the base `nvim-treesitter` highlights. And additionally plugins allow color schemes to override default behaviors by implementing specific highlights for them.

But which set and what plugins is all up to the individual.

**Comment by MeanderingProgrammer** [comment]
The green background comes from the default behavior of `RenderMarkdownH1Bg`, which links to `DiffAdd` which I'm assuming gruvbox implements as green.

**Comment by SebastianMusic** [comment]
Yes that was exactly right! i added the DiffAdd and set the background and foreground to empty and now it is properly transparent with the render-markdown.lua file
Thank you 
```lua
    overrides = {
      -- Markdown Header Background Overrides with Foreground Colors
      ['@markup.heading.1.markdown'] = { fg = '#fb4934', bg = '', bold = true },
      ['@markup.heading.2.markdown'] = { fg = '#fabd2f', bg = '', bold = true },
      ['@markup.heading.3.markdown'] = { fg = '#b8bb26', bg = '', bold = true },
      ['@markup.heading.4.markdown'] = { fg = '#8ec07c', bg = '', bold = true },
      ['@markup.heading.5.markdown'] = { fg = '#83a598', bg = '', bold = true },
      ['@markup.heading.6.markdown'] = { fg = '#d3869b', bg = '', bold = true },
      ['DiffAdd'] = { fg = '', bg = '' },
    },
```

This now does not have to be empty anymore
```lua
-- render-markdown.lua
backgrounds = {
        'RenderMarkdownH1Bg',
        'RenderMarkdownH2Bg',
        'RenderMarkdownH3Bg',
        'RenderMarkdownH4Bg',
        'RenderMarkdownH5Bg',
        'RenderMarkdownH6Bg',
      },
```
I will have to read up a bit now on treesitter thank you for the knowledge! :)

**Comment by SebastianMusic** [comment]
May have been a bit quick. adding DiffAdd only worked for the first heading. But i found that if i add these as well then every heading works
```lua
      ['DiffChange'] = { fg = '', bg = '' },
      ['DiffDelete'] = { fg = '', bg = '' },
```

**Comment by MeanderingProgrammer** [comment]
You wouldn't want to disable the diff highlight groups, since those are used in other places. Adding the per level markup headings makes sense, disabling the Diff ones for everyone does not.
I'll leave those decisions to the color scheme author though.

**Comment by SebastianMusic** [comment]
Yeah you are right. I went a little overboard. I commented out the ones for the diffs, and instead made the background colours inside of the render-markdown.lua plugin itself empty again.
```lua
-- render-markdown.lua
      backgrounds = {
        '',
        '',
        '',
        '',
        '',
        '',
      },
 
```
```lua
-- gruvbox.lua
    vim.api.nvim_create_autocmd('FileType', {
      pattern = 'markdown',
      callback = function()
        -- Markdown-specific heading highlights
        vim.api.nvim_set_hl(0, '@markup.heading.1.markdown', { fg = '#fb4934', bg = '', bold = true })
        vim.api.nvim_set_hl(0, '@markup.heading.2.markdown', { fg = '#fabd2f', bg = '', bold = true })
        vim.api.nvim_set_hl(0, '@markup.heading.3.markdown', { fg = '#b8bb26', bg = '', bold = true })
        vim.api.nvim_set_hl(0, '@markup.heading.4.markdown', { fg = '#8ec07c', bg = '', bold = true })
        vim.api.nvim_set_hl(0, '@markup.heading.5.markdown', { fg = '#83a598', bg = '', bold = true })
        vim.api.nvim_set_hl(0, '@markup.heading.6.markdown', { fg = '#d3869b', bg = '', bold = true })

        -- DiffAdd and other Diff groups specifically for Markdown
        -- vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '', bg = '' })
        -- vim.api.nvim_set_hl(0, 'DiffChange', { fg = '', bg = '' })
        -- vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '', bg = '' })
      end,
    })

```
