### ISSUE TITLE
feature: Center & Padding for text body

### ISSUE THREAD

**Issue by varo6** [MeanderingProgrammer/render-markdown.nvim#200]
### Is your feature request related to a problem? Please describe.

I was wondering if it is possible to center the written text (not codeblock or something, just normal paragraphs), not as much as center align but some padding on the left and right. The header is centered perfectly, but this adds readability for quick notes.

### Describe the solution you'd like

A good enclosure could be this one, having a margin on the left and right:
![web](https://github.com/user-attachments/assets/fd2208de-450d-4305-ad8c-aef2bad2961c)

### Describe alternatives you've considered

Maybe handling terminal padding or in neovim config works, but I don't know if it's possible enabling this only on markdown files.

**Comment by MeanderingProgrammer** [comment]
Added the feature here under a new `paragraph` configuration: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/d20d19fa54965f6eb94558c0b84fe9a942169fb4

You can try something like:

```lua
require('render-markdown').setup({
  paragraph = {
    left_margin = 0.5,
    min_width = 100,
  },
})
```

To center paragraphs.

Paragraphs are centered individually, so if you don't set a `min_width` single line paragraphs will end up not looking great.

**Comment by varo6** [comment]
Thanks! it did work, adding a paragraph render is nice too, I guess I can play with similar attributes as in the header. 
As a support, texts that are longer than one line without a break don't get the margin added, but it's not something I would need.

**Comment by MeanderingProgrammer** [comment]
Yeah, I'm not sure how to apply inline virtual text across wrapped lines. Currently I don't think it's possible, at least not easily.
