### ISSUE TITLE
Removing background colors from headings?

### ISSUE THREAD

**Issue by YousufSSyed** [MeanderingProgrammer/render-markdown.nvim#202]
I looked at the headings section and wiki page but it's not clear how to disable the background colors entirely.

**Comment by MeanderingProgrammer** [comment]
Added support for this here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/0c6de743a8d3c61b87bc7db9ab97dcda12ca6818

You just need to supply an empty table to whatever property you want to disable, so in this case:

```lua
require('render-markdown').setup({
  heading = { backgrounds = {} },
})
```

**Comment by YousufSSyed** [comment]
is opts fine? Becuase I get an error when I do this

```lua
  {
    'meanderingprogrammer/markdown.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    lazy = false,
    opts = {
      heading = {
        signs = { '#' },
			  backgrounds = {} 
      },
      bullet = {
        icons = { '-' },
      },
    }
  },
```

**Comment by MeanderingProgrammer** [comment]
What error? 

Yes it takes opts but that's more of a `lazy.nvim` thing than anything related to this plugin.

Do you use `LazyVim` the distribution, not the package manager? If so use the updated repo name `meanderingprogrammer/markdown.nvim` -> `MeanderingProgrammer/render-markdown.nvim`, no idea if it's case sensitive but may as well reduce the number of potential problems.

**Comment by MeanderingProgrammer** [comment]
Feel free to re-open if there's any follow up.

**Comment by YousufSSyed** [comment]
@MeanderingProgrammer yep updating the repo name worked, thanks.
