### ISSUE TITLE
help: Insert mode causes code block to dissappear. Setting conceallevel to 0 on Insert?

### ISSUE THREAD

**Issue by jarangutan** [MeanderingProgrammer/render-markdown.nvim#203]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

LazyVim

### Description

Hello!

I swapped to LazyVim recently and installed the LazyExtras markdown plugin which comes with render-markdown. It's awesome but I am running into a situation where the start and end of code blocks disappear when entering insert mode.

Here is normal mode with cursor in code block
![normal mode in code block](https://github.com/user-attachments/assets/9f80cd14-6f95-46c5-abe2-d421a9091b1c)

Here is insert mode with cursor in code block. Note the mermaid code block start and end went away.
![normal mode in code block](https://github.com/user-attachments/assets/262b819e-6615-4dca-b57c-361478b2ac39)

Is there a way to change the behavior so render-markdown works normally in normal mode but sets the conceallevel back to 0 in insert mode? It's a little disorienting to not see the start and end of the code block when editing.

**Comment by jarangutan** [comment]
Oh, I don't know if it matters but here's some verbose logs on the conceal levels

This is with render-markdown enabled
![Screenshot from 2024-10-11 21-01-17](https://github.com/user-attachments/assets/55989a6f-d2f3-41d6-a1eb-e2c9186ce844)

This is with render-markdown disabled. I would have thought it'd drop to 0 after disabling but it's sticking at 2
![Screenshot from 2024-10-11 21-12-08](https://github.com/user-attachments/assets/95232683-da67-45bc-b002-3fbe53d9892d)

**Comment by MeanderingProgrammer** [comment]
Hi there. This behavior is configurable through the window options config: https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki#window-options.

The default value for `conceallevel` is:

```lua
{
    win_options = {
        conceallevel = {
            default = vim.api.nvim_get_option_value('conceallevel', {}),
            rendered = 3,
        },
    },
}
```

Which means it attempts to set back the `conceallevel` to whatever you have configured when the plugin is initially loaded.

Presumably this means you set the `conceallevel` to 2 in your config or you use the LazyVim default of 2: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua#L67.

One way to fix this is to set it to 0 in your config and then you don't need to do anything with this plugin. This should also be the behavior I would expect if you disabled my plugin entirely, but it could depend on how you're changing this value.

An alternative is to set the default conceallevel to 0 in this plugin which would look like:

```lua
{
    'MeanderingProgrammer/render-markdown.nvim',
    opts = {
        win_options = { conceallevel = { default = 0 } },
    },
}
```

**Comment by jarangutan** [comment]
Oh snap, thank you for the quick response!

That was it! Sorry about that, I completely whiffed the win_options settings.
![Screenshot from 2024-10-11 21-36-13](https://github.com/user-attachments/assets/95e2e673-d039-4b4f-bc36-24ec4cfe22ab)

I've taken your suggestion to set the default conceallevel to 0 for render-markdown temporarily while I goof around with the LazyVim conceallevel to see what goofs if I set it to 0.

Thank you! Loving the plugin <3

**Comment by MeanderingProgrammer** [comment]
No worries, there's a lot of options and they're not the easiest to parse. Glad you're enjoying the plugin :)
