### ISSUE TITLE
feature: only "unconceal" at the cursorline

### ISSUE THREAD

**Issue by petobens** [MeanderingProgrammer/render-markdown.nvim#204]
### Is your feature request related to a problem? Please describe.

Consider the folllowing minimal `init.lua` file:

```lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
    {
        'MeanderingProgrammer/render-markdown.nvim',
        dependencies = {
            'nvim-treesitter/nvim-treesitter',
            'nvim-tree/nvim-web-devicons',
        },
        config = function()
            require('render-markdown').setup({
                win_options = {
                    -- FIXME: With i it shows all but with t only the cursor
                    conceallevel = { rendered = 2 },
                    concealcursor = { rendered = 'nc' },
                },
            })
        end,
    },
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        config = function()
            require('nvim-treesitter.configs').setup({
                ensure_installed = {
                    'markdown',
                    'markdown_inline',
                },
            })
        end,
    },
}

require('lazy').setup(plugins, {
    root = root .. '/plugins',
})
```

Now, as in the GIF, open nvim and edit the following `bar.md` file:
```md
# Heading 1

## Heading 2

### Heading 3
```
You will see that if you press `i` in order to get into insert mode every text in every heading is "unconceal`. 

On the other hand if I disable the plugin and just use some treesitter queries (as per https://github.com/petobens/dotfiles/blob/master/nvim/queries/markdown/highlights.scm) the ability to unconceal only at the cursor  seems to work just fine (i.e only the `Heading 3` line is unconcealed whereas `Heading 1` and `Heading 2` remain properly concealed). 

![Peek 2024-10-12 11-26](https://github.com/user-attachments/assets/974f9069-336d-4ad0-87a2-b45659bb4d40)

### Describe the solution you'd like

See above

### Describe alternatives you've considered

See above

**Comment by petobens** [comment]
Bonus: one extra thing I noticed is that if we have markdown link as in:
```md
[Google](www.google.com)
```
then when the cursor in on that line the icon disappears (even in normal mode).

![Peek 2024-10-12 11-38](https://github.com/user-attachments/assets/31da130c-e256-45d6-8822-fd15d41b9389)

**Comment by MeanderingProgrammer** [comment]
For your bonus one, the implementation as is removes everything on the cursor line, the goal is to see the actual text. There is an exception for spacing elements to avoid overly jumpy behavior, but in general the goal was to let you interact with what's actually there.

I can try out an implementation that would make what stays and what goes on the cursor line more configurable, LMK if there are any other elements, in addition to link icons, that should not be hidden away.

**Comment by petobens** [comment]
>Or if you want rendering to happen in all modes you can simply set it to true:

Great! Thanks

> I can try out an implementation that would make what stays and what goes on the cursor line more configurable

Awesome!

**Comment by MeanderingProgrammer** [comment]
`icon and language in code blocks as well as in callouts`, how would you edit these if you can't see the underlying text?

**Comment by MeanderingProgrammer** [comment]
I've made most decorations configurable in terms of what gets concealed on cursor column and what does not here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/fb6b3d145e5e12b838c0b84124354802f381b1af.

This is managed through the `anti_conceal.ignore` property. So if you do not want link icons to disappear you would set `link` to `true`. For code icon and language you would use `code_language`. And for callouts you can either keep the callout itself with `callout` or if you're referring to the block quote icon you would use `quote`. Putting these altogether you would end up with:

```lua
require('render-markdown').setup({
    anti_conceal = {
        ignore = {
            link = true,
            code_language = true,
            callout = true,
            quote = true,
        },
    },
})
```

Feel free to play around and mix and match these as you like. The complete list of decorations you can control is:

- head_icon
- head_background
- head_border
- code_language
- code_background
- code_border
- dash
- bullet
- check_icon
- check_scope
- quote
- table_border
- callout
- link
- sign

Hopefully the things they control is intuitive enough.

**Comment by petobens** [comment]
> Feel free to play around and mix and match these as you like

This is great! Thanks for the quick implementation. One minor nuisance: it possible to hide those element in normal mode but not in insert mode (or more generally respect the conceal settings)?. Looking at the following gif now you can see for instance than in the code block the `icon python` bit is not hidden in normal mode but is not hidden either in insert mode which, at least from my point of view, I find counter intuitive. 

![Peek 2024-10-13 09-06](https://github.com/user-attachments/assets/58fcfe0c-f586-4b63-a360-748647d88b59)


Since we are at, and you've been incredibly generous and patient, I'm aware of https://github.com/neovim/neovim/pull/9496 but I was wondering whether something could be made from your side to avoid this thing (with links mostly) where the conceal "extends" an extra virtual line when a window is split (as in the image below):
![image](https://github.com/user-attachments/assets/5a8fb86c-bec8-43b8-8ec9-6ddecc111cba)

**Comment by MeanderingProgrammer** [comment]
> Looking at the following gif now you can see for instance than in the code block the icon python bit is not hidden in normal mode but is not hidden either in insert mode which, at least from my point of view, I find counter intuitive.

Yeah this was my thinking when I asked:

>  how would you edit these if you can't see the underlying text?

I updated the values in `ignore`: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/29863dc5262954ea04d76bd564f2f63330b42d7f.

You can now specify a list of modes where decorations will remain when the cursor enters. So rather than specifying to hide them in insert mode, you would specify continue showing them in say normal mode with:

```lua
require('render-markdown').setup({
    anti_conceal = {
        ignore = {
            code_language = { 'n' },
        },
    },
})
```

> where the conceal "extends" an extra virtual line when a window is split (as in the image below):

I wish :( This is an issue I've gotten a few times and is also something I would love to get working but there does not seem to be a way around it: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/82, there's some links from this issue that go into more details about it, been an open issue for nearly a decade and realistically I don't think it will be fixed, kinda one of those things.

Lately I've taken to disabling line wrapping in `markdown` files as whole, since long lines are typically rare and mostly created by long links, like you mentioned. But that's more of a workaround than anything else.

If you have a concrete suggestion or something to try out I'm more than willing to take a look, but this would be an issue without my plugin if you just set the `conceallevel` to 2 or 3. And there really is not a good way to hide lines, at least that I'm aware of.

**Comment by petobens** [comment]
> You can now specify a list of modes where decorations will remain when the cursor enters.

Thanks! Works perfectly.

> there really is not a good way to hide lines, at least that I'm aware of.

I suspected that too. Thanks anyway

(feel free to close this issue, and once again thanks for the superb responses)
