### ISSUE TITLE
bug: conceallevel isn't togglable when render-markdown is toggled off

### ISSUE THREAD

**Issue by fpohtmeh** [MeanderingProgrammer/render-markdown.nvim#208]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

LazyVim

### Operating system

Windows 11

### Terminal emulator / GUI

WezTerm

### Describe the bug

LazyVim provides shortcuts to toggle render-markdown and conceal level.
Due to plugin configuration, it's not possible to have a toggleable conceal level for disabled render-markdown.

I always have 3 as the conceal level for any state of render-markdown

### Expected behavior

Conceal level changes from 3 to 0 and back for disabled render-markdown

### Healthcheck output

```text
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.3.11
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
Default LazyVim configuration
```

### Plugin error log

```text
Log is empty
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
If I'm not understanding something let me know. But based on your wording are you saying that when this plugin is disabled you still expect it to modify the conceallevel on mode changes? Or are you saying that you can't manually change the conceallevel and this plugin locks it to 3 when it's disabled?

**Comment by fpohtmeh** [comment]
Brief steps to reproduce:

- Open markdown
- Disable plugin with <leader>um
- Conceal level is 3 at this point
- Press <leader>uc to disable conceal level
Result: conceal becomes zero but immediately returns to 3, this can be visually noticed

**Comment by MeanderingProgrammer** [comment]
Ah, thanks, was able to reproduce this. Should be fixed by: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/bea6f2078e34abdf5c2632f593651bb13205477f.

**Comment by fpohtmeh** [comment]
Thank you a lot, man! ⚡
