### ISSUE TITLE
bug: conceallevel not reset when switching buffer

### ISSUE THREAD

**Issue by paulhersch** [MeanderingProgrammer/render-markdown.nvim#209]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

N/A

### Operating system

Linux

### Terminal emulator / GUI

foot

### Describe the bug

When i switch from the rendered markdown buffer to a different buffer (i have an own UI thing that uses `vim.api.nvim_win_set_buf`under the hood) the `conceallevel` for the window is not reset, which sucks if i switch from markdown to another filetype.

### Expected behavior

Conceallevel is reset when i switch buffers.

### Healthcheck output

```text
render-markdown: require("render-markdown.health").check()
 
 render-markdown.nvim [version]
 - OK plugin 7.3.11
 - OK neovim >= 0.10
 
 render-markdown.nvim [configuration]
 - OK valid
 
 render-markdown.nvim [nvim-treesitter]
 - OK installed
 - OK markdown: parser installed
 - OK markdown: highlight enabled
 - OK markdown_inline: parser installed
 - OK markdown_inline: highlight enabled
 - OK latex: parser installed
 
 render-markdown.nvim [executables]
 - OK latex2text: installed
 
 render-markdown.nvim [conflicts]
 - OK headlines: not installed
 - OK obsidian: not installed
```

### Plugin configuration

```lua
{
  enabled = true,
  latex = {
    enabled = false,
  },
  max_file_size = 5
}
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
Thanks for letting me know, turns out this was effecting some other things as well, like `oil.nvim` buffers.

Should be fixed with: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/c6b59a263cffbd6bf463fff03b28a35ad9f1a8e6
