### ISSUE TITLE
feature: Add suport for Quarto files

### ISSUE THREAD

**Issue by CRAG666** [MeanderingProgrammer/render-markdown.nvim#213]
### Is your feature request related to a problem? Please describe.

Pleace add suport for Quarto files

### Describe the solution you'd like

Only adapt code for quarto files

### Describe alternatives you've considered

This is syntax https://quarto.org/

### Additional information

cuarto doc https://quarto.org/

**Comment by MeanderingProgrammer** [comment]
Duplicate of: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/76


```lua
require('render-markdown').setup({
    file_types = { 'markdown', 'quarto' },
})
```
