### ISSUE TITLE
bug: error with charmap codec on windows

### ISSUE THREAD

**Issue by mtoons** [MeanderingProgrammer/render-markdown.nvim#214]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

N/A

### Operating system

Windows

### Terminal emulator / GUI

WezTerm

### Describe the bug

The following markdown
```

$\sqrt{a}$
```
is rendered as
```md

Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Python311\Scripts\latex2text.exe\__main__.py", line 7, in <module>
        File "C:\Python311\Lib\site-packages\pylatexenc\latex2text\__main__.py", line 199, in main
          print(ln2t.nodelist_to_text(nodelist))
        File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
          return codecs.charmap_encode(input,self.errors,encoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeEncodeError: 'charmap' codec can't encode character '\u221a' in position 0: character maps to <undefined>
    $\sqrt{a}$
```
i get similar result with \alpha i guess it has something to do with non ascii character.
![image](https://github.com/user-attachments/assets/c4671437-813c-4f9c-b205-237c845e593a)

### Expected behavior

I would have expected it to be rendered as
$\sqrt{a}$

### Healthcheck output

```text
clear:

render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.4.6
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

render-markdown.nvim [executables] ~
- OK latex2text: installed

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
{
        'MeanderingProgrammer/render-markdown.nvim',
        dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
        -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
        ---@module 'render-markdown'
        ---@type render.md.UserConfig
        opts = {},
    },
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

### Additional information

I tried switching to webdevicons instead of mini.icons

**Comment by MeanderingProgrammer** [comment]
I imagine you would get a similar error just running the CLI. What happens if you run the following in your terminal: `echo "$\sqrt{a}$" | latex2text`.

Could be the same problem as: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/47#issuecomment-2211813567

**Comment by mtoons** [comment]
Oh sorry i forgot to mention I already tried that and I do get the expected `√(a)`.
```pwsh
echo "$\sqrt{a}$" | latex2text
```
```
√(a)
```
![image](https://github.com/user-attachments/assets/71ecfcde-ea3d-43bd-bb38-2dc97510d64d)
