### ISSUE TITLE
feature: list of lists for 'ordered list icons' in configuration as well

### ISSUE THREAD

**Issue by greyHairChooseLife** [MeanderingProgrammer/render-markdown.nvim#218]
### Is your feature request related to a problem? Please describe.

Not related to a problem, but just improvement.

### Describe the solution you'd like

I've noticed the recent commits, 

- 04e75a3 for _feat: allow bullet icons to be a list of lists_ from the request #217
- 14673b0 for _feat: support adding icons to ordered lists_

While the changes from 04e75a3 make the unordered lists more flexible, I believe the power of 'list of lists' should also be applied to ordered lists.

It seems the author of #217 might agree. It looks like he's aimed at extending the use of 'unordered list' to 'ordered list'

### Describe alternatives you've considered

N/A

**Comment by MeanderingProgrammer** [comment]
Ordered list icons already support list of lists, just like unordered lists. The docs didn't mention this feature so have updated that.
