### ISSUE TITLE
help: Only Highlighting Code Borders

### ISSUE THREAD

**Issue by thecontinium** [MeanderingProgrammer/render-markdown.nvim#220]
### Neovim version (nvim -v)

v0.11.0-dev-4192+g7a7747f1e4-Homebrew

### Neovim distribution

Custom LazyVim

### Description

Hi 
I would like to be able to only highlight the borders on the code blocks and not the code itself.
Is this possible ?
Thanks

**Comment by MeanderingProgrammer** [comment]
Added support for this here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/bee16b21bf47b64ceda8c9bb281d4b576d329c0f

You can configure it by setting `code.disable_background` to `true`:

```lua
{
    'MeanderingProgrammer/render-markdown.nvim',
    opts = {
        code = { disable_background = true },
    },
}
```

**Comment by thecontinium** [comment]
Great - thanks. I’ll give it a spin.

--
***@***.***
