### ISSUE TITLE
bug: code block not rendered correctly

### ISSUE THREAD

**Issue by cliffxuan** [MeanderingProgrammer/render-markdown.nvim#221]
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

N/A

### Operating system

Ubuntu VM sshed into from Windows

### Terminal emulator / GUI

Windows Terminal

### Describe the bug

For a code block header
- the ``` is not concealed
- the language name is not concealed and therefore duplicated
![image](https://github.com/user-attachments/assets/ad7312f6-8b2b-4506-ab4a-32ffd53e8d6b)

### Expected behavior

the header of the code block should conceal the ``` and the language name

### Healthcheck output

```text
==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- ERROR markdown: highlight not enabled
- OK markdown_inline: parser installed
- ERROR markdown_inline: highlight not enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
lazy.nvim

  {
    'MeanderingProgrammer/render-markdown.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' },
    ft = 'markdown'
  },
```

### Plugin error log

```text
markdown.nvim: unexpected command: log
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

### Additional information

I tried older commits and it's working before this commit https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/fcd908bafb96e4a30ab

![image](https://github.com/user-attachments/assets/7b18f3cc-8e95-45ac-8ce4-922057644a87)

**Comment by MeanderingProgrammer** [comment]
Please look at the errors in your health check and enable treesitter highlights

**Comment by cliffxuan** [comment]
@MeanderingProgrammer thanks! enabled treesitter hightlight and it's working as expected :)
