### ISSUE TITLE
help: Trying to change heading highlight color

### ISSUE THREAD

**Issue by Cole-Hartman** [MeanderingProgrammer/render-markdown.nvim#225]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

Kickstart

### Description

I am trying to mess with the config to change the heading color. For example when I render a heading 1 I want it to be yellow. I've been looking trough the readme and the wiki and can't seem to find this configuration.

**Comment by MeanderingProgrammer** [comment]
These are provided by your colorscheme and come from the definitions for `@markup.heading.1.markdown` -> `@markup.heading.6.markdown`.

You can override your colorschemes values for these likely via some config option or redefine them after running your colorscheme using the `vim.api.nvim_set_hl` API.
