### ISSUE TITLE
Help: Use this plugin only in LSP hover buffers

### ISSUE THREAD

**Issue by marcelarie** [MeanderingProgrammer/render-markdown.nvim#226]
### Neovim version (nvim -v)

v0.11.0-dev-1092+g0da4d89558

### Neovim distribution
- None

### Description

I would like to use this plugin only for lsp hover buffers.
Is there a way of only render the markdown on a buftype `nofile` + `markdown` file type?

I thought about something like this:
```lua
opts = {
  file_types = {
    "markdown",
    "Avante",
  },
  exclude = {
    buftypes = { "" }, -- normal files do not have a buftype
  },
}
```

But it does not work

Thanks!

**Comment by MeanderingProgrammer** [comment]
Ah the `exclude` option was removed in the 6.0.0 release in favor of a more powerful `overrides` option which in addition to letting you disable based on `buftype` / `filetype` lets you change individual settings. This was to support disabling signs in LSP hover docs out of the box. https://github.com/MeanderingProgrammer/render-markdown.nvim/releases/tag/v6.0.0.

It's a little more cumbersome to do just the disable but here's how it would look:

```lua
opts = {
  file_types = { "markdown", "Avante" },
  overrides = { buftype = { [""] = { enabled = false } } },
}
```

**Comment by marcelarie** [comment]
That is exactly what I needed, thanks!
