### ISSUE TITLE
feature: support getting language icon by extension

### ISSUE THREAD

**Issue by chrisgrieser** [MeanderingProgrammer/render-markdown.nvim#233]
### Neovim version (nvim -v)

NVIM v0.10.2

### Neovim distribution

N/A

### Operating system

macOS 15.1 (arm)

### Terminal emulator / GUI

Neovide

### Describe the bug

only longform codeblock labels work, short form ones are not. 

````
```py
print("Hello")
```

```python
print("Hello")
```
````

<img alt="Showcase" width=50% src="https://github.com/user-attachments/assets/b4bac09c-b0ce-4ca2-b99c-0feeffedd151">

### Expected behavior

Both should be rendered correctly, since both are valid for GitHub (i.e., both get correct syntax highlighting from GitHub).

### Healthcheck output

```text
render-markdown.nvim [version] ~
- OK plugin 7.5.4
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- ERROR Failed to run healthcheck for "render-markdown" plugin. Exception:
  .../lazy/render-markdown.nvim/lua/render-markdown/state.lua:202: attempt to call method 'for_each' (a nil value)
```

### Plugin configuration

```lua
-- don't think this is relevant, but nonetheless, here:
		opts = {
			render_modes = { "n", "c", "i", "v", "V" },
			bullet = {
				icons = { "▪️", "▫️", "•", "◦" },
			},
			heading = {
				icons = {}, -- disables icons
			},
			code = {
				border = "thick",
				position = "left",
			},
			sign = { enabled = false },
			win_options = {
				-- toggling this plugin should also toggle conceallevel
				conceallevel = { default = 0, rendered = 3 },
			},
		},
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
Currently we only support getting by language name. Whether or not GitHub supports something or not does not make this a bug, the goal is not feature parity with GitHub. 

Supporting extensions as a fallback is a reasonable feature request, I'll see what I can do. Currently we use the following APIs depending on icon provider:

- For `mini.icons` we call `get('filetype', language)`
- For `nvim-web-devicons` we call `get_icon_by_filetype(language)`

**Comment by MeanderingProgrammer** [comment]
I'm interested in the error you're getting in the healthcheck:

```
- ERROR Failed to run healthcheck for "render-markdown" plugin. Exception:
  .../lazy/render-markdown.nvim/lua/render-markdown/state.lua:202: attempt to call method 'for_each' (a nil value)
```

I'm not sure how this is possible and curious how you're getting it. It seems like somehow the `health.lua` file is out of sync with the `state.lua` file.

The only way to have version `7.5.4` in the output is to be on the latest commit: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/d69a885e1bf21cb329d2eafe56fd80b6de627216.

But the error about `for_each on line 202` is only possible if your `state.lua` file is the one prior to that commit, so the files are from different commit.

Did `lazy.nvim` run into any errors when updating? If you try to update again and run the healthcheck do you still get the error?

**Comment by chrisgrieser** [comment]
> Did lazy.nvim run into any errors when updating? If you try to update again and run the healthcheck do you still get the error?

Ran it again on the same commit, got no errors this time:

```
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.5.4
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

**Comment by MeanderingProgrammer** [comment]
Huh, I wonder what happened the first time, maybe an edge case due to updating without restarting neovim?

Files that had already been used in the session like `state.lua` were using the older version since those were cached and files that had not been used yet like `health.lua` and the validator pulled the newer version.

At least that would kind of make sense but just a guess on my part. Glad it's working in either case!

**Comment by MeanderingProgrammer** [comment]
Should work after: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/78a2eb7fc273f36790aa390262f390a3265eedff

**Comment by chrisgrieser** [comment]
Thank you!
