### ISSUE TITLE
feature: Option to disable logs

### ISSUE THREAD

**Issue by polirritmico** [MeanderingProgrammer/render-markdown.nvim#235]
### Is your feature request related to a problem? Please describe.

Hi! great plugin!

Currently there's no option to disable the log mechanism. Personally, I don't care about the logs of a UI enhancement plugin unless I'm trying to address some kind of issue or providing details for a bug report.

### Describe the solution you'd like

Add an "off" option to completely disable the log generation.

### Describe alternatives you've considered

Maybe even consider the use of `vim.log.levels` to the config like other plugins (e.g. Neotest, Conform, Mason) as it already provides DEBUG, ERROR, WARN and OFF levels definitions (but also INFO and TRACE):

```lua
log_level = vim.log.levels.OFF, -- or WARN, etc.
```

**Comment by MeanderingProgrammer** [comment]
Sure, added here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/48a52dd5c847c59eac6ae5b96ff0123acd1a394d.

For the time being I like having a separate definition since values like `TRACE` and `WARN` have no meaning. So you'll need to set a value of 'off'.

```lua
require('render-markdown').setup({
    log_level = 'off',
})
```
