### ISSUE TITLE
bug: attempt to index local 'first' (a nil value)

### ISSUE THREAD

**Issue by kapral18** [MeanderingProgrammer/render-markdown.nvim#236]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

LazyVim

### Operating system

MacOS 15.1

### Terminal emulator / GUI

Kitty

### Describe the bug

This happened after being away (focus out) from main nvim window for a long time and getting back in with an already open markdown file.

![image](https://github.com/user-attachments/assets/fe020da6-8df7-4025-9eed-d6c17c38eadc)

```
Error
executing
vim. schedule lua callback: ...ender-markdown.nvim/lua/render-markdown/render/table.lua:357: attempt to index local 'first' (a nil value)
stack traceback:
...ender-markdown.nvim/lua/render-markdown/render/table.lua:357: in
function
...ender-markdown.nvim/lua/render-markdown/render/table.lua:210: in function
"full'
"render'
..r-markdown.nvim/lua/render-markdown/handler/markdown.lua:81: in function
'callback'
..ender-markdown.nvim/lua/render-markdown/core/context.lua:207: in function
'query'
..r-markdown.nvim/lua/render-markdown/handler/markdown.lua:76: in function
'parse'
... azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:217: in function
'parse_tree'
... azy/render-markdown.nvim/lua/render-markdown/core/ui.lua: 187: in
function
... azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:124:
in
'parse_buffer'
function
'run_update"
...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:88: in function <...azy/render-markdown.nvim/lua/render-markdown/core/ui. lua:87>
```

### Expected behavior

no error

### Healthcheck output

```text
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.5.5
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```
```


### Plugin configuration

```lua
My plugin config:
https://github.com/kapral18/dotfiles/blob/e2ee989779e8fa9dc0752710152cf070ce448acb/home/dot_config/exact_nvim/exact_lua/exact_plugins/markdown.lua#L6

Lazyvim config my config points to:
https://github.com/LazyVim/LazyVim/blob/704c29110d578186f0ca3eac67b753ddf52541fc/lua/lazyvim/plugins/extras/lang/markdown.lua#L96
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
With something like this I would need a minimal reproducible example with very specific steps that consistently trigger the error, otherwise I'm just shooting blindly.

I found one potential source of this and fixed that here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/7f0143e9adf7140c8e3fa33a5bdf193d7a8f0429, but can't say for sure if this fixes the problem since I can't replicate it.

Anecdotally I've left files open in different windows for many hours without interacting with them, gone back with no issues. So if I had to guess there might be some plugin trying to save resources by unloading idle treesitter parsers or entire buffers, and something is going on there. But I really can't say anything for sure.
