### ISSUE TITLE
help: anyway to put an icon on the end of headings?

### ISSUE THREAD

**Issue by Giessen** [MeanderingProgrammer/render-markdown.nvim#238]
### Neovim version (nvim -v)

0.11.0-dev-3c803483a

### Neovim distribution

lunarvim

### Description

anyway to put an icon on the end of headings? Thanks for any instruction.

**Comment by MeanderingProgrammer** [comment]
There is not a way to put icons at the end. Will give the feature some thought.

**Comment by MeanderingProgrammer** [comment]
Added this here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/e1879e0ea3d5cee295b48335fc90e76ae8a63081

You can set it with:

```lua
require('render-markdown').setup({
    heading = { position = 'right' },
})
```

**Comment by Giessen** [comment]
Thank you very much. Is it possible to allow ending icon in overlay mode? I find the indentation is good for navigation.
