### ISSUE TITLE
feature: support for mdx files

### ISSUE THREAD

**Issue by No0ne003** [MeanderingProgrammer/render-markdown.nvim#239]
### Is your feature request related to a problem? Please describe.

plugin doesn's work on mdx files

### Describe the solution you'd like

addding support to .mdx files

### Describe alternatives you've considered

I tested writing "markdownx" and "mdx" on `file_types` on the plugin confige but it doesn't work

**Comment by MeanderingProgrammer** [comment]
Duplicate of: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/120

LMK if any of that works for.

MDX as far as I know doesn't have a standard out of the box setup for neovim so how did you get any form of syntax highlighting working? 

When you open an `mdx` file what is the output of this command: `:lua vim.print(vim.bo.filetype)`?

**Comment by No0ne003** [comment]
thanks the plugin work in the mdx files now 
about the MDX highlighting It's not working for me either 
and the `:lua vim.print(vim.bo.filetype)` command now output `mdx`

**Comment by No0ne003** [comment]
update: syntax highlighting on `mdx` files is working for me now I think because of registering mdx on treesitter
