### ISSUE TITLE
feature: Render footnotes

### ISSUE THREAD

**Issue by einarpersson** [MeanderingProgrammer/render-markdown.nvim#241]
### Is your feature request related to a problem? Please describe.

I use footnotes in my notes and it would be nice if it would be rendered by this _wonderful_ plugin.

To quote [this post](https://obsidian.rocks/footnotes-in-obsidian/):

> For a little while now I’ve been using footnotes in Obsidian. I think they’re a bit of a “hidden feature”. They’re [in the documentation](https://help.obsidian.md/How+to/Format+your+notes#Footnotes), but for some reason I rarely see people use them.
...
> [using footnotes] allows your ideas to flow out of you more naturally, and you don’t have to worry about restructuring your note to fit previous modes of thought.

Also note that [Github now supports footnotes](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) in their markdown, so this is not "just Obsidian".

It would be a great addition imho which shouldn't be too hard to implement, I think?

Thanks again for a great plugin!

### Describe the solution you'd like

```md
Sam[^1] is almost two years old.

## Footnotes
[^1]: Sam is my son 
```

should be rendered as

```md
Sam⁽¹⁾ is almost two years old.

## Footnotes
⁽¹⁾: Sam is my son 
```

Paranthesis have to be used instead of brackets as (to my knowledge) you can't use brackets in superscript utf8 (or?). But I think paranthesis are alright.

### Describe alternatives you've considered

Just having it as is.

### Additional information

- Perhaps there are some configuration options, but as a first step I propose just implementing the above.

- Note that the main obstacle with footnotes is creating / formatting / maintaining them, but this is not the scope of this plugin. There are other plugins that can help with that.

- Note: Only caret symbols `[^....]` should be rendered this way, as to not interfer with other things

**Comment by MeanderingProgrammer** [comment]
Thank you for the kind words, glad you are enjoying the plugin!

Added this feature here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/634acd5da964c32f6947cd0c7802d7a116662665

LMK if this is what you had in mind!

**Comment by einarpersson** [comment]
That was quick! Yes that was what I was asking for. Thanks a lot!

**Comment by MeanderingProgrammer** [comment]
Sure, updated the behavior here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/1b5d11734122d9451d2e5e2e567fd61a62822293

The `prefix` and `suffix` are now configurable for footnotes. By default both are set to the empty string.
