### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by guoliang** [MeanderingProgrammer/render-markdown.nvim#243]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

kickstart

### Operating system

MacOS

### Terminal emulator / GUI

WezTerm

### Describe the bug

The following markdown isn't rendered correctly if it ends with a number

```markdown
_works_

_does not work9_

```

### Expected behavior

the second example should render as the first one 
<img width="128" alt="image" src="https://github.com/user-attachments/assets/cfc8f0ec-6bb7-4fe8-a190-a64dafede3a5">

### Healthcheck output

```text
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.6.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: installed but should not conflict
```

### Plugin configuration

```lua
{
    'MeanderingProgrammer/render-markdown.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' },
  },
```

### Plugin error log

```text
2024-10-03 08:47:35 ERROR [fail 50] - no treesitter parser found
2024-10-04 11:22:03 ERROR [fail 40] - no treesitter parser found
2024-10-07 13:39:36 ERROR [fail 156] - no treesitter parser found
2024-10-09 09:16:17 ERROR [fail 17] - no treesitter parser found
2024-10-09 09:16:18 ERROR [fail 1] - no treesitter parser found
2024-10-17 13:14:12 ERROR [fail 127] - no treesitter parser found
2024-10-17 13:52:47 ERROR [fail 127] - no treesitter parser found
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
Issue in the underlying tree-sitter parser, more details here: https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/8
