### ISSUE TITLE
feature: add a way to disable code borders while keeping `opts.code.style = "language"`

### ISSUE THREAD

**Issue by loqusion** [MeanderingProgrammer/render-markdown.nvim#246]
### Is your feature request related to a problem? Please describe.

`opts.code.style = "full"` looks quite nice on an opaque background. But on a transparent background, it's a different story...

![image](https://github.com/user-attachments/assets/749fcca6-85a4-4e4c-bb7c-ea77faba1603)

This can be mitigated somewhat with `opts.code.style = "language"`:

![image](https://github.com/user-attachments/assets/957f74bd-6b7b-45b6-b2e2-06a1dae4fa21)

And then by setting `opts.code.highlight = "Normal"`:

![image](https://github.com/user-attachments/assets/dde03461-18a9-4161-a5c2-b1709be821fe)

But the bottom border still persists.

There's also the nuclear option of `opts.code.style = "none"`, but then we miss out on the language icon + name.

### Describe the solution you'd like

Subjectively, I think `opts.code.style = "language"` should disable the borders entirely with no extra configuration needed.

### Describe alternatives you've considered

If that's not an option, then perhaps a new configuration property in `opts.code` could be added. (But this places more burden on plugin users.)

**Comment by MeanderingProgrammer** [comment]
Added `none` as an option for `code.border` here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/f3cda24c71261f6a52f5ddafb95786684d862d87.

I'll rethink the `language` style behavior at some point in the future, debating how to handle styles in general. I may remove them or treat them more as presets, still not decided, leaning towards the latter.

You can use the `language` style along with the new `border` value or if you want consistent behavior that doesn't change when I modify style value behaviors you can use `disable_background` to remove the background from code blocks, so your config would look like:

```lua
require('render-markdown').setup({
    code = {
        disable_background = true,
        border = 'none',
    },
})
```
