### ISSUE TITLE
help: i can't change pipe_table style

### ISSUE THREAD

**Issue by manzup3r** [MeanderingProgrammer/render-markdown.nvim#247]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

LazyVim

### Description

I'm trying to change the pipe_style preset to double. I tried to copy paste the code that's in the wiki, but after reloading nvim it doesn't change the pipe_style, I still have the default setting. Am I doing something wrong? 

Here's my config:

return {
  "MeanderingProgrammer/render-markdown.nvim",
  dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" },
  opts = {
    preset = "lazy",
    file_types = { "markdown", "Avante" },
    code = {
      enabled = true,
      sign = true,
      style = "full",
      position = "left",
      language_pad = 0,
      language_name = true,
      disable_background = { "diff" },
      width = "full",
      left_margin = 0,
      left_pad = 0,
      right_pad = 0,
      min_width = 0,
      border = "thin",
      above = "▄",
      below = "▀",
      highlight = "RenderMarkdownCode",
      highlight_inline = "RenderMarkdownCodeInline",
      highlight_language = nil,
    },
    bullet = {
      enabled = true,
      icons = { "●", "○", "◆", "◇" },
      ordered_icons = {},
      left_pad = 0,
      right_pad = 0,
      highlight = "RenderMarkdownBullet",
    },
    checkbox = {
      enabled = true,
      position = "inline",
      unchecked = {
        icon = "󰄱 ",
        highlight = "RenderMarkdownUnchecked",
        scope_highlight = nil,
      },
      checked = {
        icon = "󰱒 ",
        highlight = "RenderMarkdownChecked",
        scope_highlight = nil,
      },
      custom = {
        todo = { raw = "[-]", rendered = "󰥔 ", highlight = "RenderMarkdownTodo", scope_highlight = nil },
        important = { raw = "[*]", rendered = "󰓎 ", highlight = "DiagnosticWarn" },
      },
      quote = { repeat_linebreak = true },
      win_options = {
        showbreak = { default = "", rendered = "  " },
        breakindent = { default = false, rendered = true },
        breakindentopt = { default = "", rendered = "" },
      },
      pipe_table = { preset = "double" },
      sign = {
        enabled = true,
        highlight = "RenderMarkdownSign",
      },
      indent = {
        enabled = false,
        per_level = 2,
        skip_level = 1,
        skip_heading = false,
      },
    },
    heading = {
      enabled = true,
      sign = true,
      position = "inline",
      icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
      signs = { "󰫎 " },
      width = "full",
      left_margin = 0,
      left_pad = 0,
      right_pad = 0,
      min_width = 0,
      border = false,
      border_virtual = false,
      border_prefix = false,
      above = "▄",
      below = "▀",
      backgrounds = {
        "RenderMarkdownH1Bg",
        "RenderMarkdownH2Bg",
        "RenderMarkdownH3Bg",
        "RenderMarkdownH4Bg",
        "RenderMarkdownH5Bg",
        "RenderMarkdownH6Bg",
      },
      foregrounds = {
        "RenderMarkdownH1",
        "RenderMarkdownH2",
        "RenderMarkdownH3",
        "RenderMarkdownH4",
        "RenderMarkdownH5",
        "RenderMarkdownH6",
      },
    },
  },
  ft = { "markdown", "Avante" },
}

**Comment by MeanderingProgrammer** [comment]
I popped your config in a formatter which makes the problem more obvious:

```lua
    {
        'MeanderingProgrammer/render-markdown.nvim',
        dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' },
        opts = {
            preset = 'lazy',
            file_types = { 'markdown', 'Avante' },
            code = {
                enabled = true,
                sign = true,
                style = 'full',
                position = 'left',
                language_pad = 0,
                language_name = true,
                disable_background = { 'diff' },
                width = 'full',
                left_margin = 0,
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = 'thin',
                above = '▄',
                below = '▀',
                highlight = 'RenderMarkdownCode',
                highlight_inline = 'RenderMarkdownCodeInline',
                highlight_language = nil,
            },
            bullet = {
                enabled = true,
                icons = { '●', '○', '◆', '◇' },
                ordered_icons = {},
                left_pad = 0,
                right_pad = 0,
                highlight = 'RenderMarkdownBullet',
            },
            checkbox = {
                enabled = true,
                position = 'inline',
                unchecked = {
                    icon = '󰄱 ',
                    highlight = 'RenderMarkdownUnchecked',
                    scope_highlight = nil,
                },
                checked = {
                    icon = '󰱒 ',
                    highlight = 'RenderMarkdownChecked',
                    scope_highlight = nil,
                },
                custom = {
                    todo = { raw = '[-]', rendered = '󰥔 ', highlight = 'RenderMarkdownTodo', scope_highlight = nil },
                    important = { raw = '[*]', rendered = '󰓎 ', highlight = 'DiagnosticWarn' },
                },
                quote = { repeat_linebreak = true },
                win_options = {
                    showbreak = { default = '', rendered = ' ' },
                    breakindent = { default = false, rendered = true },
                    breakindentopt = { default = '', rendered = '' },
                },
                pipe_table = { preset = 'double' },
                sign = {
                    enabled = true,
                    highlight = 'RenderMarkdownSign',
                },
                indent = {
                    enabled = false,
                    per_level = 2,
                    skip_level = 1,
                    skip_heading = false,
                },
            },
            heading = {
                enabled = true,
                sign = true,
                position = 'inline',
                icons = { '󰲡 ', '󰲣 ', '󰲥 ', '󰲧 ', '󰲩 ', '󰲫 ' },
                signs = { '󰫎 ' },
                width = 'full',
                left_margin = 0,
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = false,
                border_virtual = false,
                border_prefix = false,
                above = '▄',
                below = '▀',
                backgrounds = {
                    'RenderMarkdownH1Bg',
                    'RenderMarkdownH2Bg',
                    'RenderMarkdownH3Bg',
                    'RenderMarkdownH4Bg',
                    'RenderMarkdownH5Bg',
                    'RenderMarkdownH6Bg',
                },
                foregrounds = {
                    'RenderMarkdownH1',
                    'RenderMarkdownH2',
                    'RenderMarkdownH3',
                    'RenderMarkdownH4',
                    'RenderMarkdownH5',
                    'RenderMarkdownH6',
                },
            },
        },
        ft = { 'markdown', 'Avante' },
    }
```

Lots of the options (`quote`, `win_options`, `pipe_table`, `sign`, `indent`) are incorrectly nested under `checkbox`.

As a general tip if you're using the default values for options, like most of the `heading` & `code` values, you are always going to be better off leaving them blank, makes debugging easier and less likely to experience problems from breaking changes. If you're only changing some values in a config you don't need to include all the other default ones, only the ones you want to change.

**Comment by manzup3r** [comment]
thx, i was racking my head over this, didn't even notice the formatting was wrong,, fix😅
