### ISSUE TITLE
help: Post-render callback

### ISSUE THREAD

**Issue by nmder** [MeanderingProgrammer/render-markdown.nvim#248]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

N/A

### Description

Hi there,

I was looking to render the latex formulas with `nabla.nvim`. I got it working thanks to the instructions on this repo and some modification to the nabla.nvim plugin. However, the latex must be rendered after rendering the markdown to account for the icon width, indentation, etc. Is there any way to achieve a post-render callback to achieve this?

I tried the usual `on.attach` callback, but it does not work as the callback happens much earlier.

Thanks in advance!

**Comment by MeanderingProgrammer** [comment]
Can you provide a screenshot of how it looks now, preferably one with some obvious problems. Along with the configuration for both this plugin and nabla.

**Comment by nmder** [comment]
Sorry for the delayed response.

Here is the render with the next config:
<img width="897" alt="image" src="https://github.com/user-attachments/assets/62eaadb1-0686-4ad6-863c-6c1f0b1e9b23">
```lua
  {
    "MeanderingProgrammer/render-markdown.nvim",
    ft = { 'markdown' },
    dependencies = {
      'nvim-tree/nvim-web-devicons',
      'nvim-treesitter/nvim-treesitter',
      'nmder/nabla.nvim',
    },
    config = function ()
      vim.api.nvim_set_hl(0, 'myRenderMarkdownCode', { bg = '#22252B' })
      require('render-markdown').setup {
        latex = { enabled = false },
        render_modes = { 'n', 'c', 't', 'i' },
        win_options = { conceallevel = { rendered = 2 } },
        on = {
          attach = function()
            -- vim.defer_fn(
            --   function ()
                require('nabla').enable_virt({ autogen = true })
              -- end, 100)
          end,
        },
        sign = {
          enabled = false,
        },
        code = {
          highlight = 'myRenderMarkdownCode',
        }
      }
    end
  },
```
In the line 3 of the above screenshot, you may notice that the exponents `x` are above the base. This is caused by the lack of accounting of the concealed and inline virtual texts added by  render-markdown.

Now, with the commented part in the above config, with `defer_fn`, I am scheduling a delayed rendering by nabla (a modded version as the existing repo does not work well, as it is parsing the document as a latex file to identify the math zones with is messing up code blocks with shell variables; the original also did not account for the concealed and inline virtual text to properly place the exponents in the virtual line above). This generates the following proper rendering:
<img width="952" alt="image" src="https://github.com/user-attachments/assets/54a2e545-b369-413a-b0aa-2784360463d3">

Same results can be achieved by entering and exiting insert mode on a line without an affected math environment.

Therefore, a post-render callback could be useful to achieve a proper rendering pipeline.

**Comment by MeanderingProgrammer** [comment]
Gotcha, makes sense. Added `on.render` option here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/c89e5e0719d07e1e2c0d3942b564ac916b6ffe9c.
