### ISSUE TITLE
bug: Codeblocks and quote blocks have weird interactions

### ISSUE THREAD

**Issue by theahura** [MeanderingProgrammer/render-markdown.nvim#249]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

NA

### Operating system

Ubuntu 24

### Terminal emulator / GUI

Terminal

### Describe the bug

Syntax highlighting with quote blocks seems to be broken. 

See the following markdown. Note that I have added backslashes to make sure this renders on github, but feel free to ignore them -- they aren't present in the actual markdown I am trying to render
```
> \```python
>
> def foo(bar):
>   print('help')
> \```

Foo bar baz blah

\```python
def foo(bar):
  print('help')
\``` 

```

which currently renders like this:

![image](https://github.com/user-attachments/assets/e382d300-44aa-45df-8abd-d42ebe12e598)

Notice that there is no syntax highlighting in the quote block, nor anything after that. Notice too that the 'python' language tag is doubled.

If I remove the quote block from the first code block:

```

\```python
def foo(bar):
  print('help')
\```

Foo bar baz blah

\```python
def foo(bar):
  print('help')
\```

```

Then I get the correct highlighting
![image](https://github.com/user-attachments/assets/9158eb98-f560-4ee3-bc0f-4992b1f081b2)

### Expected behavior

I would expect the code block within the quote block to be properly highlighted, or at least not to cause problems downstream.

### Healthcheck output

```text
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.6.9
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- ERROR markdown: highlight not enabled
- OK markdown_inline: parser installed
- ERROR markdown_inline: highlight not enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
{
        'MeanderingProgrammer/render-markdown.nvim',
        opts = {
          file_types = { "markdown", "Avante" },
        },
        ft = { "markdown", "Avante" },
      },
```

### Plugin error log

```text
NA
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

### Additional information

I'm not sure if this is actually an issue with _markdown_ compared to this particular package. I notice that github's markdown renderer ALSO has issues with code blocks in quote blocks...

**Comment by MeanderingProgrammer** [comment]
Please read the errors in your health check and enable nvim-treesitter highlights

**Comment by theahura** [comment]
Potentially a stupid question: how do I enable the nvim-treesitter highlights? 

I added the following to my nvim-treesitter config:
```
      {
        "nvim-treesitter/nvim-treesitter",
        opts = {
          ensure_installed = { "markdown", "markdown_inline" }, -- Parsers to install
          highlight = {
            enable = true, -- Enable treesitter-based highlighting
          },
        },
      },
```

But this does not seem to change the result of the checkhealth. 
      
FWIW, it seems like that _is_ the issue -- if I use `TSBufEnable highlight` manually, the syntax highlighting gets fixed

**Comment by MeanderingProgrammer** [comment]
Oh, I'm not 100% sure, but I don't think the opts config works for `nvim-treesitter`, since the main method doesn't follow the standard naming pattern. Can you try:

```lua
{
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
        require('nvim-treesitter.configs').setup({
            ensure_installed = { 'markdown', 'markdown_inline' },
            highlight = { enable = true },
        })
    end,
}
```

**Comment by theahura** [comment]
Yep, looks like thats the right track. 

I ended up using the config from the suggested lazy.nvim treesitter plugin docs  -- looks like lazy.nvim as a package manager specifically does have some issues with treesitter highlighting, cf https://github.com/nvim-treesitter/nvim-treesitter/issues/6831

The lazy.nvim treesitter config is here: https://www.lazyvim.org/plugins/treesitter

and the piece that was necessary to get it to work was:
```
        ---@param opts TSConfig
        config = function(_, opts)
          require("nvim-treesitter.configs").setup(opts)
        end,
 ```
 
 So my full config looks like:
 
 ```
       {
        "nvim-treesitter/nvim-treesitter",
        opts = {
          highlight = { enable = true },
          indent = { enable = true },
          ensure_installed = {
            "bash",
            "c",
            "diff",
            "html",
            "javascript",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "printf",
            "python",
            "query",
            "regex",
            "toml",
            "tsx",
            "typescript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
          },
        },
        ---@param opts TSConfig
        config = function(_, opts)
          require("nvim-treesitter.configs").setup(opts)
        end,
      },
      ```
      
      Thanks a ton for the help @MeanderingProgrammer, happy to close this out
