### ISSUE TITLE
feature: Preview ordered lists in normal mode

### ISSUE THREAD

**Issue by mfbehrens** [MeanderingProgrammer/render-markdown.nvim#250]
### Is your feature request related to a problem? Please describe.

In Markdown, it is common to write ordered lists as

```markdown
1. first element
1. second element
1. third element
```

which is correctly rendering to:

1. first element
1. second element
1. third element

e.g. see [markdownguide.org](https://www.markdownguide.org/basic-syntax/#ordered-lists)

`render-markdown.nvim` unfortunately does not render this in normal mode.

### Describe the solution you'd like

When I exit edit mode and look at the document in normal mode, all numbers are corrected to their actual number.

### Describe alternatives you've considered

Use the markdown preview in the browser

**Comment by MeanderingProgrammer** [comment]
There was a way to do this, it just wasn't enabled by default. You would do something like:

```lua
require('render-markdown').setup({
  bullet = {
    ordered_icons = { { '1', '2', '3', '4', '5', '6', ... } },
  },
})
```

However doing this for long lists would be tedious so I added support for functions to be the value along with a default implementation that probably does what you were looking for here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/a7097f372ba8f8866cda5e98d5bc828f2856c96c
