### ISSUE TITLE
help:  duplicate module on luarocks.org

### ISSUE THREAD

**Issue by ambaradan** [MeanderingProgrammer/render-markdown.nvim#252]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

rocks.nvim

### Description

Hi, I was intending to write the 'rockspec' for the plugin “tadmccorkle/markdown.nvim” and realized that on luarocks the name is already occupied by your plugin. Since yours is now called “render-markdown.nvim” and since the module in question is currently a duplicate I was wondering if it would be possible to delete from *luarocks.org* the module so that I could try to write the rockspec for that plugin.
Thank you

**Comment by MeanderingProgrammer** [comment]
Done, I kept it around to allow users to migrate over. I think enough time has passed at this point, module has been deleted.

**Comment by ambaradan** [comment]
Many thanks and good work
