### ISSUE TITLE
Disable link concealing?

### ISSUE THREAD

**Issue by Oneechan69** [MeanderingProgrammer/render-markdown.nvim#253]
Since the issue of link wrapping and virtual text can't be fixed, can I disable concealing markdown links at all? When I do the following, it doesn't work. The concealing is only disabled if I disabled the plugin entirely.

```lua
    opts = {
			link = {
				enabled = false
			},
    }
```

**Comment by MeanderingProgrammer** [comment]
You asked this same question in this discussion: https://github.com/MeanderingProgrammer/render-markdown.nvim/discussions/231, and seem to have ignored my answer.

**Comment by Oneechan69** [comment]
I forgot 😢😢😢
