### ISSUE TITLE
bug: E5108 "Invalid buffer" whe toggle the render

### ISSUE THREAD

**Issue by sadtab** [MeanderingProgrammer/render-markdown.nvim#260]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

My own

### Operating system

Ubuntu

### Terminal emulator / GUI

Alacritty

### Describe the bug

When several markdown files are opened and some of them are modified with or without writing , toggling the renderer  can cause this error log : 

```
   Error  04:11:20 PM msg_show.emsg E5108: Error executing lua: ...y/render-markdown.nvim/lua/render-markdown/core/util.lua:131: Invalid buffer id: 4
stack traceback:
	[C]: in function 'nvim_buf_get_name'
	...y/render-markdown.nvim/lua/render-markdown/core/util.lua:131: in function 'file_name'
	...zy/render-markdown.nvim/lua/render-markdown/core/log.lua:61: in function 'buf'
	...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:79: in function 'update'
	...azy/render-markdown.nvim/lua/render-markdown/manager.lua:47: in function 'set_all'
	...im/lazy/render-markdown.nvim/lua/render-markdown/api.lua:17: in function 'toggle'
	/home/sadegh/.config/nvim/lua/helpers.lua:47: in function </home/sadegh/.config/nvim/lua/helpers.lua:44>
```
I looked a little in the source code and it seems the autocmd at 
https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/e41b0002fe4196825450ab5a6343300c40791d51/lua/render-markdown/manager.lua#L18

is registered in all files and if somehow there is a temporary buffer that comes into existence and is wiped out right  after (maybe another plugin is doing it) is queued in the plugin internals

I changed autocmd to 

```lua
    vim.api.nvim_create_autocmd('FileType', {
        pattern = { 'markdown' },
        group = M.group,
        callback = function(args)
            M.attach(args.buf)
        end,
    })
```
And it seems to be working, I see this autocmd is intentionally registered for all the files but maybe there is a better way of doing it

### Expected behavior

no invalid buffer error

### Healthcheck output

```text
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.7.3
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled

render-markdown.nvim [executables] ~
- OK none to check

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
{
    "MeanderingProgrammer/render-markdown.nvim",
    dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" },
    opts = {
      file_types = { "markdown", "noice" },
      -- enabled = false, -- Disable by default
      code = {
        sign = false,
        width = "block",
        -- right_pad = 1,
        style = "full",
        language_pad = 0,
        language_name = true,
        position = "right",
      },
      dash = {
        -- Turn on / off thematic break rendering
        enabled = true,
        icon = "󰮸 ",
        width = 40, -- textwidth/2 because of 2 characters as icon
        highlight = "RenderMarkdownDash",
      },
      heading = {
        enabled = true,
        width = "block",
        sign = false,
        icons = {
          -- "󰎤  ",
          -- " 󰎩  ",
          -- "  󰎪  ",
          -- "   󰎮  ",
          -- "    󰎱  ",
          -- "      󰎵  ",
          "",
          "",
          "",
          "",
          "",
          "",
        },
        -- left_margin = 2,
      },
      bullet = {
        -- Turn on / off list bullet rendering
        enabled = true,
        right_pad = 1,
      },
      latex = {
        enabled = false,
        -- Executable used to convert latex formula to rendered unicode
        converter = "latex2text",
        -- Highlight for LaTeX blocks
        highlight = "RenderMarkdownMath",
        -- Amount of empty lines above LaTeX blocks
        top_pad = 0,
        -- Amount of empty lines below LaTeX blocks
        bottom_pad = 0,
      },
      win_options = {
        conceallevel = {
          default = 0,
          rendered = 3,
        },
      },
      render_modes = { "n", "c", "t", "i" },
    },
    ft = { "markdown", "norg", "rmd", "org", "noice" },
  },
```

### Plugin error log

```text
```
   Error  04:11:20 PM msg_show.emsg E5108: Error executing lua: ...y/render-markdown.nvim/lua/render-markdown/core/util.lua:131: Invalid buffer id: 4
stack traceback:
	[C]: in function 'nvim_buf_get_name'
	...y/render-markdown.nvim/lua/render-markdown/core/util.lua:131: in function 'file_name'
	...zy/render-markdown.nvim/lua/render-markdown/core/log.lua:61: in function 'buf'
	...azy/render-markdown.nvim/lua/render-markdown/core/ui.lua:79: in function 'update'
	...azy/render-markdown.nvim/lua/render-markdown/manager.lua:47: in function 'set_all'
	...im/lazy/render-markdown.nvim/lua/render-markdown/api.lua:17: in function 'toggle'
	/home/sadegh/.config/nvim/lua/helpers.lua:47: in function </home/sadegh/.config/nvim/lua/helpers.lua:44>
```
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by sadtab** [comment]
The problem still exists even with my modification, it is way less frequent but I particularly see it in DiffView ing the MD files. 

> [!INFO]
> In DiffView ing, the ft is still markdown

**Comment by sadtab** [comment]
At some point, we need to add a `if vim.api.nvim_buf_is_valid(buf) then` in the logics

**Comment by sadtab** [comment]
Experimenting with : 
```lua
function M.set_all(enabled)
    -- Attempt to attach current buffer in case this is from a lazy load
    M.attach(util.current('buf'))
    state.enabled = enabled
    for _, buf in ipairs(buffers) do
        if vim.api.nvim_buf_is_valid(buf) then
            ui.update(buf, vim.fn.bufwinid(buf), 'UserCommand', true)
        end
    end
end
```

at https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/e41b0002fe4196825450ab5a6343300c40791d51/lua/render-markdown/manager.lua#L43

**Comment by MeanderingProgrammer** [comment]
Thanks for letting me know!

This should resolve it: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/0022a579ac7355966be5ade77699b88c76b6a549

**Comment by sadtab** [comment]
You're awesome
