### ISSUE TITLE
help: Is it possible to completely turn off link rendering?

### ISSUE THREAD

**Issue by TC-MO** [MeanderingProgrammer/render-markdown.nvim#261]
### Neovim version (nvim -v)

0.10

### Neovim distribution

lazyVim

### Description

Is it possible to turn off links rendering, while retaining all other functionality?

I tried

```lua
{
  "MeanderingProgrammer/render-markdown.nvim",
  opts = {
    link = {
      enabled = false
    }
  },
}
```

But it doesn't seem to do the trick.

**Comment by palandovalex** [comment]
```lua
{
  "MeanderingProgrammer/render-markdown.nvim",
  opts = {},
  config = function()
    require("render-markdown").setup({
      link={enabled=false},
    })
  end
}
```

**Comment by palandovalex** [comment]
sorry...

When i look to this fragment in `README.md` , i was bit confused:
```lua
setup({
    link = {
        -- Turn on / off inline link icon rendering
        enabled = true,
    }
})
```
paramet `enabled` inside `link` table - is definitely not intuitive. The comments directly confirm this. When I gave you advice, I didn't pay attention to the comment, the code looked clear and understandable. But in fact, it was misleading. The comments directly confirm this. By logics, it should manage all links rendering, not rendering icons.
I think, this isue must be treated as bug.

Comletly disable link rendering - shoul look like this:
```lua
setup({
    link = false,
})
```
or like this:
```lua
setup({
    link = {enabled = false},
})
```
If i want turn on/off link icon:
setup({
    link = {
        -- Turn on / off inline link icon rendering
        icons_rendering=false,
    }
})
But now, i have no ideas, how to solve this problem.

**Comment by MeanderingProgrammer** [comment]
What link rendering behavior are you trying to disable?

The only link rendering this plugin does is adding icons, the comment in the README is meant to clarify this, though I can see why it would be confusing. No it is not a bug.

Are you referring to the conceal behavior? If so this behavior is going to come from the rendered `conceallevel` setting as well as your treesitter highlights most likely coming from `nvim-treesitter`. You can see more details on this in my response in this discussion: https://github.com/MeanderingProgrammer/render-markdown.nvim/discussions/231.

LMK if there was some other behavior you were referring to!
