### ISSUE TITLE
feature: add google sheets/docs/presentation custom icons to links

### ISSUE THREAD

**Issue by petobens** [MeanderingProgrammer/render-markdown.nvim#263]
### Is your feature request related to a problem? Please describe.

Is it possible to add fancy icons to google sheets, docs and presentations? Basically links of the following form:

- https://docs.google.com/spreadsheets/...
- https://docs.google.com/presentation/...
- https://docs.google.com/document/...

Currently they are all shown with the same icon:

![image](https://github.com/user-attachments/assets/9bb7a8fa-92ff-4a8b-b5a7-b9cc0506ed19)

### Describe the solution you'd like

Use icons that allow us to differentiate between a document, a spreadsheet and a presentation.

### Describe alternatives you've considered

..

**Comment by MeanderingProgrammer** [comment]
You can already do this by adding more custom links to your config: https://github.com/MeanderingProgrammer/render-markdown.nvim?tab=readme-ov-file#links. These are built using lua-patterns, for example:

```lua
require('render-markdown').setup({
    link = {
        custom = {
            spreadsheets = { pattern = 'docs%.google%.com/spreadsheets', icon = '<some_fancy_icon>' },
            presentation = { pattern = 'docs%.google%.com/presentation', icon = '<some_fancy_icon>' },
            document = { pattern = 'docs%.google%.com/document', icon = '<some_fancy_icon>' },
        },
    },
})
```

**Comment by petobens** [comment]
Thank you!
