### ISSUE TITLE
question: why are quotes in json strings concealed

### ISSUE THREAD

**Issue by oblitzitate** [MeanderingProgrammer/render-markdown.nvim#264]
### Neovim version (nvim -v)

v0.11.0-dev-1189+g989a37a594

### Neovim distribution

N/A

### Operating system

Linux

### Terminal emulator / GUI

Kitty

### Describe the bug

It is annoying to edit JSON code within the code block when the quotes don't show up until the cursor is on the line.

### Expected behavior

JSON code should not be concealed.

### Healthcheck output

```text
==============================================================================
render-markdown:                     require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.7.4
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- ERROR headlines: installed
- OK obsidian: installed but should not conflict
```

### Plugin configuration

```lua
Default config
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
Nothing to do with this plugin. This is just the behavior of setting a `conceallevel` > 0 and the default `json` highlights from `nvim-treesitter`: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/json/highlights.scm.

You can override this behavior by creating a custom `highlights.scm` in your config and removing the 2 conceal queries, i.e.:

```
; https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/json/highlights.scm minus conceal queries

[
  (true)
  (false)
] @boolean

(null) @constant.builtin

(number) @number

(pair
  key: (string) @property)

(pair
  value: (string) @string)

(array
  (string) @string)

[
  ","
  ":"
] @punctuation.delimiter

[
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

(escape_sequence) @string.escape
```

**Comment by oblitzitate** [comment]
Thanks for the workaround. Although, I don't think a workaround should be needed. There's almost certainly no good reason to conceal JSON string quotes when editing them.

Anyways, even if I put `conceallevel` to 0 in my base config, this plugin still conceals the JSON quotes. It seems the plugin modifies the `conceallevel` when it's active.

So given it modifies that, would you also consider modifying it so that the JSON string quotes are concealed by default?

**Comment by MeanderingProgrammer** [comment]
Yes this plugin modifies conceallevel when rendering vs not rendering a file. This is to hide link destinations as well as many other features which require the ability to conceal content. It uses your config's value when not rendering and a value of 3 when rendering by default, you can modify this by setting:

```lua
require('render-markdown').setup({
    win_options = { conceallevel = { rendered = 0 } },
})
```

> So given it modifies that, would you also consider modifying it so that the JSON string quotes are not concealed by default?

You can use the above setting to disable concealing, no workaround needed.  However concealing is an all or nothing setting at the window level, it cannot be toggled at a per line or per language level. Lots of features of this plugin rely on the ability to conceal content, hence why the default is set to 3. If you modify this value and don't like the results you'll need to use the workaround of overriding the default highlights. If you don't like the fact you need a workaround to turn off quote concealing then submit a PR to `nvim-treesitter` to remove these values from the default json highlights. 

This plugin does not intentionally conceal quotes, it is a side effect of the defaults shipped with `nvim-treesitter` and the need to conceal content to make rendering possible.
