### ISSUE TITLE
rendering not working in neovim for superscript, subscript, emoji and footnotes 

### ISSUE THREAD

**Issue by mairs8** [MeanderingProgrammer/render-markdown.nvim#266]
### Is your feature request related to a problem? Please describe.

I am new to markdown and this plugin. I was expecting the superscript, subscript, emoji and footnotes features to work (expected image below) but it just shows the markdown format in neovim (current image below). Is there something i am missing?

Current:
![screenshot_](https://github.com/user-attachments/assets/e6e45577-f16e-44ef-8433-59dd810be32f)

Expected: 
![screenshot_](https://github.com/user-attachments/assets/8c0bfb00-f14e-4747-90d1-df35185f9b53)

### Describe the solution you'd like

rendering of the markdown within neovim per above images.

### Describe alternatives you've considered

did not find anything in the wiki on superscript, subscript, emoji and footnotes.

**Comment by MeanderingProgrammer** [comment]
The footnotes should work, at least to the extent that they appear as superscripts. You'll need to use the following markdown syntax:

```
Footnote Link [^1]

[^1]: Some Info
```

If that doesn't work try updating the plugin.

In general this plugin does not do anything with HTML with the exception of comments. So `<sub>` / `<sup>` tags are ignored.

Emojis would require some way to resolve text to unicode for the symbol which I do not want to maintain, I believe there are some other plugins that do something like this.
