### ISSUE TITLE
just a question, is there any practical differences between this and markview?

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [MeanderingProgrammer/render-markdown.nvim#271]
### Neovim version (nvim -v)

nah

### Neovim distribution

nah

### Description

 I am in the process of rewriting my config, and if there are differences that interest me, I might jump ship

**Comment by MeanderingProgrammer** [comment]
I don't keep up with `markview` enough to give this a fair answer, so I'll go with nah, no practical difference, it's all just preferences.

I'd say give both a shot and pick the one you prefer, whether one feels more responsive, looks nicer, is more configurable, or whatever it is that matters to you.

If `markview` is doing everything you want and trying things out "without a good reason" isn't something you're interested in that's fair enough, stick with `markview`.

**Comment by 4rtemis-4rrow** [comment]
thank you for the answer, I'll give this plugin a shot, see how it feels
